### ISSUE TITLE
Show user related activities in Profile

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#102]
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Product-and-UX-design-circles.garden-(Circles-myxogastria)?type=design&node-id=7523-11365&mode=design&t=yPVTJsS38AsNIaUw-0 from Lucia

**Comment by louilinn** [comment]
@triaslucia 
I found the issue relating to profile mutual activity. It was never implemented
https://github.com/CirclesUBI/circles-myxogastria/blob/82caa6cfc6bbd8376f4af4ad4255e51ab36eb688/src/views/Profile.js#L265

Is there a design for how this should look?

I haven't had time to check yet how much functionality is missing to access the necessary data.  So if there is no design yet, no rush. Let's set priority first.

**Comment by llunaCreixent** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/circles-myxogastria/102?planning-poker) with Zenhub @louilinn @mikozet
