### ISSUE TITLE
Add tutorial for Magic Words (Seed phrase)

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#107]

**Comment by triaslucia** [comment]
**In the current state user have no idea what Seed phrase AKA. Magic Words are, and how to deal with it**
The _Magic Words_ is for most of the people something completely new. So we need to be supportive in two main things: 
a_ Explain what these are, and make clear these is just a password, so tpeople relate to something to already known. And this way we avoid, the fear of entering a highly complex security world they won't understand.
b_ Give practical ideas for saving it. 

**We should implement a  _Macig Words_ tour**
I want people to be guided through the different reasons why we use it.
I want people to be given concrete practical examples on how to save it.

**Describe alternatives you've considered**
1_People has no password manager or similar to save complex passwords or log-in infos. 
2_People are used to come up with vvery short eassy passwords, mostly related to personal information, so remembering random words is not possible. 
3_

**Design Material** _BLUE:_ https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/circles-myxogastria?node-id=3820%3A19832

**Comment by triaslucia** [comment]
This is related to a re-design of the entire process of creating a Wallet. Could you see it @adzialocha  and see if its doable to be implemented until lunching? 
If not we can go step-by-step. Do the seed phrase tutorial now and see the rest later.
