### ISSUE TITLE
Uploaded camera images are sometimes flipped 90degrees when uploading avatar

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#113]

**Comment by triaslucia** [comment]
This is still an issue, but we have no clear reproduction of the issue so far. 
So far we noticed it happens on the first time of uploading a picture, and get corrected when changing it through edit profile flow. It happen on computer.

**Comment by triaslucia** [comment]
I tried to reproduced this bug, on preview with edit profile feature and did not happened again.

**Comment by triaslucia** [comment]
this bug is not possible to be reproduced anymore. Might already been solved, when the "edit profile" got implemented.
