### ISSUE TITLE
Changes aren't perisisting

### ISSUE THREAD

**Issue by fabianhjr** [CirclesUBI/circles-myxogastria#123]
There is an issue were trusting/untrusting identities aren't getting persisted. (Even when the UI confirms "succesfully" trustring/untrusting someone) Tried to reset cache and relog into cricles.garden.

Upon inspecting it, there seems to be an authorization issue on an enpoint
![Screenshot from 2020-10-18 16-04-43](https://user-images.githubusercontent.com/303897/96385814-eb299880-115b-11eb-9350-43ddc4163e19.png)
![Screenshot from 2020-10-18 16-07-10](https://user-images.githubusercontent.com/303897/96385826-01cfef80-115c-11eb-83b2-9f78738ce02b.png)

```
POST | https://relay.circles.garden/api/v1/safes/0xblablabla/transactions

Response body:
TransactionServiceException: b'\x08\xc3y\xa0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x16Invalid owner provided\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by adzialocha** [comment]
We're looking into an issue with our relayer @fabianhjr not updating the transaction states, which causes different states between the safe nonce and the nonce the relayer knows about. It shows up as this error in the app as the signature is wrong (not really helpful I know). Will get back soon with updates!

**Comment by johanbove** [comment]
This issue seems to be related to the Firefox browser. On Chrome based browser all is working well.
