### ISSUE TITLE
Login / Seed Entry Case Sensitvity Issue

### ISSUE THREAD

**Issue by fabianhjr** [CirclesUBI/circles-myxogastria#126]
> The seed entry form is caps sensitive and many people will have the first word auto capitalized.
> Its a easy UX fix that would improve many peoples experience

This issue was reported by Rob on the Telegram General Chat: https://t.me/CirclesUBIGeneralChat/13950

**Comment by adzialocha** [comment]
Thank you for the report! This issue should have been fixed here: https://github.com/CirclesUBI/circles-myxogastria/blob/main/src/views/Onboarding.js#L172. Also related: https://github.com/CirclesUBI/circles-myxogastria/issues/118
