### ISSUE TITLE
Maximum amount that I'm able to send to people seems to always be 0

### ISSUE THREAD

**Issue by Powersource** [CirclesUBI/circles-myxogastria#133]
*Guessing* this is likely related to the overloaded servers but maybe it's me misunderstanding how stuff works.

I've created my account, am trusted by a few people and I trust a few people, but when I go to send someone circles the max I can send them seems to always be 0, which makes it so I can't send circles.

Anyway congrats on the launch! Looking forward to these initial issues getting resolved :)

**Comment by adzialocha** [comment]
Huhu @Powersource! :smile_cat: Yes, its related to a few issues mostly concerning the size of the trust network and required refactorings to deal with this, we're on a good path with:

1. Using a native process to calculate the trust path https://github.com/CirclesUBI/circles-transfer
2. Rewriting the api logic to be more granular with trust limit updates: https://github.com/CirclesUBI/circles-api/pull/24

We hope to release this in the next days!

**Comment by Powersource** [comment]
Thanks for the info,

and it seems to work to send loops now :grinning: :shrug:
