### ISSUE TITLE
Share profile link directs to a 404 page on netlify

### ISSUE THREAD

**Issue by eminx** [CirclesUBI/circles-myxogastria#139]
When I have created the account (but not yet received the sufficient/any trust), I have the option to share my profile with the "Share Profile Link" button at the bottom of the page. However, the link that is generated with the accompanying text leads to an unfound page.

My experience with Netlify suggests that this may have to do with redirecting all requests to home/index page for SPAs: https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps

When I tried to reproduce, to take a screenshot, it then actually redirected back to the validation page... :/

**Comment by eminx** [comment]
I can however see that netlify configuration is already in place at `netlify.toml` file, so it's pretty weird I encountered that I think...

**Comment by ana0** [comment]
Can you share a link that reproduces this? Profile links seem to be working on my end

**Comment by adzialocha** [comment]
This is expected behavior as invalidated accounts can only see the validation screen (nothing else, including own profile pages). Could be a ux improvement to allow looking at your own profile at that stage but this might open up some more onboarding flow ux questions.

**Comment by eminx** [comment]
Sorry for the late response. Just noticed your answers...
Right now it redirects to the home page, which I think is because I'm not verified yet.
It makes sense so I'll close the issue!
