### ISSUE TITLE
Does not display mutually trusted peers and claims there are none when there are

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#180]
**Describe the bug**
Incorrectly tells user that another untrusted user "is not trusted by anyone you trust" when it is.

**To Reproduce**
1. Go to another user that is trusted by someone you trust 
2. The UI tells you that noone you trust trusts this user
3. Trust the user
4. You can now can now see mutually trusted users correctly

**Expected behavior**
Mutually trusted peers should be displayed instead of this incorrect message

**Screenshots**
Before trusting
![image](https://user-images.githubusercontent.com/20553836/115557073-9e14b380-a2b1-11eb-9d32-aa3b729e5eeb.png)
After trusting
![image](https://user-images.githubusercontent.com/20553836/115557765-53e00200-a2b2-11eb-8fe7-f3aa2e7626ff.png)
After untrusting
![image](https://user-images.githubusercontent.com/20553836/115557073-9e14b380-a2b1-11eb-9d32-aa3b729e5eeb.png)

**Desktop-Computer (please complete the following information):**
 - Firefox

**Comment by triaslucia** [comment]
Check if this is still an issue . In case it's not fixed, its priority 2.
