### ISSUE TITLE
Should we add also lower case characters ([a-z]) in "formUsernameInvalidFormat"?

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#181]
In the text for the views, the [field "formUsernameInvalidFormat"](https://github.com/CirclesUBI/circles-myxogastria/blob/organizational-wallets/locales/en.json#L326) might suggest that lower case characters are not valid.

**Comment by adzialocha** [comment]
Related: https://github.com/CirclesUBI/circles-api/issues/35 and then change the text to something less cryptic! :sun_with_face: (not sure that adding more weird characters like `az AZ` will make it clear to users? I wonder if there is a simple formulation one can just use)
