### ISSUE TITLE
Searching for an org shouldn't have trust option

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#185]
When searching for an org in the wallet, the org correctly appears but it has the trust button. This gives an error when clicking it because it isn't possible to trust an org (they have no token). This feature should not be in the UI for orgs.

**Comment by adzialocha** [comment]
Interesting, this must be a bug, thought we've fixed it with this: https://github.com/CirclesUBI/circles-myxogastria/blob/organizational-wallets/src/components/ProfileMini.js#L147, did you see this issue in preview.circles.garden or circles.garden @louilinn ?
