### ISSUE TITLE
Shared Wallets tutorial doesn't load in the second attemp of creating an shared wallet

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#186]
**Describe the bug**
Shared Wallets tutorial doesn't load in the second attempt of creating an Org account. It happens regardless whether I created an org or if I cancelled the process.

**To Reproduce**
1. Go to `/organization`
2. Navigate through the tutorial
3. Close the org creation view, or finish the creation of a shared wallet, or reload the page (all three cases leads to the same state where you cannot see the tutorial again)
4. I can only see the tutorial again if I re-login

**Expected behavior**
I expect having a way to see the tutorial again. Perhaps, adding a button that says "skip tutorial" can be useful if I don't really want to see it again.
Maybe the behavior is actually expected.

**Comment by adzialocha** [comment]
This is actually not a bug but a feature, we keep track of "already visited tutorials" and don't show them a second time as we thought the user already "learned" everything and can skip this step :smile:
