### ISSUE TITLE
"Back" button should bring you to the main page of the app

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#187]
**Describe the bug**
"Back" button should bring you to the main page of the app instead to the previous url visited.

**To Reproduce**
1. Go to `https://circles.garden/profile/<a-profile-address>`
2. Click on the arrow button place on the top-left corner

**Expected behavior**
I expect being redirected to `https://circles.garden`.

**Comment by louilinn** [comment]
Closed as duplicate of https://github.com/CirclesUBI/circles-myxogastria/issues/565
