### ISSUE TITLE
"Issue Circles" is confusing and not consistent with general wording

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#197]
* Group wallets do not "issue" Circles
* Isn't "issuing" the act of generating new Circles with one owns token? Its confusing to use it for  "sending" Circles

**Comment by triaslucia** [comment]
For "send to " and "Send from" we should use **send** instead of **issue**

**Comment by triaslucia** [comment]
@adzialocha you change this!

**Comment by adzialocha** [comment]
> For "send to " and "Send from" we should use send instead of issue

Okay, so just for clarification @triaslucia : The heading and buttons still say "issue" or "issue Circles" while the input fields will say "Send to" and "Send from"?

**Comment by eminx** [comment]
I'm totally agreeing with the points in the first message of this issue.

Since it wasn't clear, I just made a new PR with changing all "Issue/Issued" wordings to "Send/Sent". 

Let me know if you had something else in mind!
