### ISSUE TITLE
It is not clear how to trust people as an organization

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#198]
It is not clearly visible how to trust users when being logged in as an organization. There is a "Search users" navigation item in the sidebar, which is maybe too deeply buried plus the naming is not ideal?

**Comment by triaslucia** [comment]
Change current  menu entry "Search users" to "Trust people"

**Comment by adzialocha** [comment]
> Change current menu entry "Search users" to "Trust people"

I agree that this is a good change but I don't think it covers the UX problem here: Users don't find easily how to find other users at all when being logged in as an organization. I guess its because the search bar is missing on the dashboard for them?

I've moved this change into an own ticket: https://github.com/CirclesUBI/circles-myxogastria/issues/222

**Comment by triaslucia** [comment]
this got solved with the new landing page design
