### ISSUE TITLE
Wrong text color on "continue" button on Enter email screen 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#200]
**Short explanations**
When creating a new account on the circles.garden there is a coloring error on the "continue button" of the Enter email screen.
When the function of continue gets activated the text turn into dark-purple and it should be white. 

**To do**
Change the color of the "Continue" word into: #FFFFFF 

<img width="1789" alt="Screenshot 2021-06-25 at 13 05 44" src="https://user-images.githubusercontent.com/38475134/123416585-0a17de80-d5b7-11eb-98e6-a624a2152f78.png">

**Comment by eminx** [comment]
This seems to be the case only on Safari, and intermittently... Opera/Chrome is fine.

I'm taking a look into it now...

![Screenshot 2021-07-06 at 16 46 02](https://user-images.githubusercontent.com/22205310/124611300-ee51e980-de8e-11eb-823f-61a4ba79f3ae.png)

**Comment by adzialocha** [comment]
Related: https://github.com/mui-org/material-ui/issues/26251

**Comment by adzialocha** [comment]
I've applied the workaround discussed in the Material UI issue and pushed it here: https://github.com/CirclesUBI/circles-myxogastria/pull/219
