### ISSUE TITLE
"Shared link profile" gets broken after two times clicking

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#201]
**"Shared link profile" gets broken after two times clicking**
After clicking two times on the "shared link profile" button the menu with the option does not appear anymore. Leaving as the only option to share the profile the QR code. 

**To Reproduce**
1. Go to 'Show your QR code or profile to others to receive trust.'
2. Click on 'Share Profile Link'
3. See error: when copying the clipboard text it says: 

**Expected behavior**
a_The display menu should appear as many times as people click this button.
b_ The profile link should be copied as clipboard text. 

**Desktop-Computer (please complete the following information):**
 - MacOS: Mojave
 - Browser: safari
 -Version 14.1.1

**Comment by louilinn** [comment]
check if it can still be reproduced

**Comment by triaslucia** [comment]
I tried to reproduce this bug and it is fixed.
