### ISSUE TITLE
Org onboarding tutorial states wrongly that "groups can trust other groups"

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#203]
Since organizations do not have a Token they can not be trusted. Still it says in the app: "As a group you can trust other groups." during the onboarding / tutorial process when creating a new organizational wallet.

For this screen we would need different copy.

**Comment by triaslucia** [comment]
NEW TEXT 
 
As a group you can trust people in order to accept their Circles. You can also send and receive Circles from other groups. [Learn more on how to organize with other groups. ](https://handbook.joincircles.net/docs/communities)

**Comment by adzialocha** [comment]
Fixed via https://github.com/CirclesUBI/circles-myxogastria/commit/4ed7fd4a2e43ae10773ea86161074a0bebf9abdd
