### ISSUE TITLE
Remove emails from onboarding

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#208]
We don't check for the validity of email addresses currently and in general there are other options to interact with our users, for example:

* Physical and virtual Assemblies
* Modals in the wallet with latest news / updates and calls for action

**Comment by adzialocha** [comment]
Related issue: https://github.com/CirclesUBI/circles-myxogastria/issues/209

**Comment by louilinn** [comment]
Conflicting interest on this
Needed for e.g. Dead man's switch communication but long term this is on the radar
