### ISSUE TITLE
Update the Issue circles screen’s design  

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#211]
Make the design like presented on the Figma file. 

Wider and one round corner. 

**Design file | Marked with yellow color**

https://www.figma.com/file/xqLKVIJTMAKuwO2wYGbyeb/Shared-Wallets?node-id=1928%3A4

**Comment by adzialocha** [comment]
We finished giving all Dialogs a rounded border in https://github.com/CirclesUBI/circles-myxogastria/pull/212 and made the sending dialog slightly larger: https://github.com/CirclesUBI/circles-myxogastria/pull/217
