### ISSUE TITLE
Add a refreshing notification for crashed processes

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#238]
So far for payment process and for trust process:. both processes where getting regullarly stucked on our last testing. The idea will be to add a "Refreshing pop up notification" so people do not think their account doesn't work anymore. 

NOTE: mostly this happend when people blocked their phones. Re open it and wanted to rightaway make a transaction or trust somebody. 

_Design Material_  BLACK: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/circles-myxogastria?node-id=3820%3A19832

**Comment by louilinn** [comment]
Note to self:
Try removing this line and see if that gives same problem:
https://github.com/CirclesUBI/circles-myxogastria/blob/main/src/store/onboarding/actions.js#L142

**Comment by triaslucia** [comment]
related to https://github.com/CirclesUBI/circles-myxogastria/issues/253
