### ISSUE TITLE
Change text  on the searching  box

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#239]
On the main screen of the wallet we hace the peolpe searching box. 
The text written in there is: Add and Search contact. 
Actually we don't use the temrinology Add nore contacts, but trust and people. SO the new text should be: 

"Trust and Search for people"

_Design Material_ LIGHT GREEN: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/circles-myxogastria?node-id=3820%3A19832

**Comment by louilinn** [comment]
@triaslucia Just double checking, do we want to include the word trust here at all or simple "Search for people" as this is what the bar does, what you write into the search bar wont be trusted directly
(or "Search for people to trust and transfer to")

**Comment by triaslucia** [comment]
no longer valid. We have a new design.
