### ISSUE TITLE
Indication of which wallet / account you are currently using

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#240]
It is unclear / confusing which wallet you are using until you go to send and it says which account you are sending from. It is thus also unclear who you are trusting as. Is it all you wallets / "accounts" or which one of them? (it is one of them but it's unclear from a user perspective)

This could be added to the dialogue of confirming a trust connection. I also think it is worth considering having an indication of which account you are currently using at the top at all times to know which account you are currently using (especially for users with multiple accounts).

related issues: #204 #198

**Comment by triaslucia** [comment]
I will close this as it will be resolved when implementing the new design.
