### ISSUE TITLE
Add information of the current state of the Shared Wallets creation process

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#243]
After the user introduces all the information needed to create a shared wallet, the app stays in hold for few minutes while all the steps are being carried on. We could add a progress bar and some text of the steps in the loading page:
Step 1: Register a to-be-created Safe in the Relayer and receive a predicted Safe address.
Step 2: Register username and email address and connect it to a Safe address in off-chain database.
Step 3: Deploy the Safe for the Organization in the blockchain.
Step 4: Create organization account in the Hub.
Step 5: Create a 100% trust connection from the organization to the user.
Step 6: Prefund the organization with Tokens from the user.

The name of the steps are quite technical, so they should probably be reformulated in a more user friendly way. I leave this for you @triaslucia. 😺

**Comment by louilinn** [comment]
Handled here:
https://github.com/CirclesUBI/circles-myxogastria/issues/266
