### ISSUE TITLE
Increase possible image size of profile picture uploads

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#248]
**Is your feature request related to a problem? Please describe.**
Image upload often fails because the maximum size is 1 MB. This is now clearly communicated but UX can be improved further

**Describe the solution you'd like**
Allow for larger images (maybe 5MB or more) and shrink them before sending to backend database

**Comment by llunaCreixent** [comment]
@mikozet are we compressing the image to 5 MB, or 1 MB?

**Comment by mikozet** [comment]
@llunaCreixent to 1 MB :)

**Comment by louilinn** [comment]
Is this solved then? @mikozet

**Comment by mikozet** [comment]
I believe it is. We solved problem another way. User may upload photo which size is more than 1mb but we compress it before sending to backend.
