### ISSUE TITLE
Change account creation process 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#262]
We will implement a new Ux and UI design of our creating Wallet flow. 
Includes:

- New process dived in 3 steps
- New visuals
- Reactive design, name and picture appear in place when people add them. 

**Design Material**
_Marked in red_  https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A18052

**Comment by JacqueGM** [comment]
Pending review by @louilinn

**Comment by mikozet** [comment]
This PR contains work for two tasks:
https://github.com/CirclesUBI/circles-myxogastria/issues/315
as well as
https://github.com/CirclesUBI/circles-myxogastria/issues/262
