### ISSUE TITLE
Re-design of the Validation process

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#263]
Implement a re design of the verification process. 

-add a direct notification of who trusted you
**Design Material**
_Marked in green_ https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A18052

**Comment by mikozet** [comment]
Hi Lucia!
We don't have 'Create account' button anymore. Currently once we have 3 confirmation user have to click `Create account` button which brings him to next screen. Do we miss it or once user has 3 connections he should automatically be redirected to next screen?
![Zrzut ekranu 2022-03-24 o 16 00 51](https://user-images.githubusercontent.com/95082155/159946262-ff920aba-03c7-437a-bc09-0439e59aa50a.png)

**Comment by mikozet** [comment]
PR lacks of functionality where we display image and name of trusted users. Additional task has been created to accommodate that: https://github.com/CirclesUBI/circles-myxogastria/issues/325
