### ISSUE TITLE
Re-designing landing page of the wallet 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#264]
New design of Landing page. It has 3 levels of engagement:
1_Trust people and send circles
2_ ... Menu ( quick enries to edit profile, marketplace, support)
3_ Burger menu ( stays at it was) 

**Deisng Material**
_Marked in brown:_ https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4356%3A49547

**Comment by mikozet** [comment]
Resolved in this PR:
https://github.com/CirclesUBI/circles-myxogastria/pull/324

**Comment by triaslucia** [comment]
There are a few aspect of the landing page (dashboard) that have to be reconsider. 

1_The Balance displaying- the idea of circle is not working for Wallets holding lots of circles. 

2_Scrolling option should be made visible. 
     2.1_ Every time a screen can be scrolled, there should always appear the pink shadow at the button of the screen. 
     2.2_ In the hovering, the scrolling side bar should be made visible. And the bar should remain visible as long as the scrolling action is happening. The scrolling side-bar should disappear once people interacts with other part of the screen.
    2.3_Scroll only contacts, rest is fixed (scroll messes up top of page with line and name and image over balance)  

3_ There are changes on the colour of Shared Wallets. 

4_Menu:
4.1_max sizes (Desktop version) should be corrected.
4.2_Colour should be changed. On individual wallets changes to plain skyblue. On shared Wallets changes to plain Violet. 
4.3_Support does not work 
4.4_Edit profile does not work 

5_Menu button colour should be changed. On individual wallets changes to plain skyblue. On shared Wallets changes to plain Violet. 


**Design Material** _https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4356%3A49547
