### ISSUE TITLE
Create stepper component

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#268]
Create a stepper component in order to use in "Re-design of Shared Wallets Creation process #266" https://github.com/CirclesUBI/circles-myxogastria/issues/266

https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A18052
![Zrzut ekranu 2021-12-13 o 11 42 55](https://user-images.githubusercontent.com/95082155/145798555-e3899859-d1d0-41e3-8651-7e90af8cf5b8.png)
![Zrzut ekranu 2021-12-13 o 11 42 46](https://user-images.githubusercontent.com/95082155/145798558-4c98025c-f98e-4cb7-92d4-b4cacb5e7aa6.png)

**Comment by triaslucia** [comment]
@mikozet  is this still and open Issue? We are creating all components on the library so we will take care of this as well.

**Comment by mikozet** [comment]
Hi @triaslucia,

This is done I believe

**Comment by louilinn** [comment]
We as developers should close our issues when they are done :)
