### ISSUE TITLE
Load more button on Activity tab doesn't show any new items after clicking it

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#272]
New users have very little activities. On activity tab there is `load more` button which after clicking doesn't load any new items. What is expected is that if there are no new items to show to user we shouldn't display `load more` button

**Comment by louilinn** [comment]
Lucia agrees to remove load more when not more is available

**Comment by mikozet** [comment]
In current behaviour Load more button will be showed incorrectly only when remeaning items of user is equal to page size. So for example if we display 10 items per page and user have 10 total items Load more button will be showed incorectly (as there is no more items to show). If total items are 20 at the second page Load more button will be showed incorrectly. In other cases it disappears correctly.

Problems occurs in Activity and Mutual activities
for example:
/profile/0x559379752eE03b8C4644B2B353fecdd836e41A97
/activities?category=transfers

**Comment by louilinn** [comment]
Resolved :)
