### ISSUE TITLE
When log out, "circles-production-mainnet-privateKey" in local storage has a value

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#273]
When you log out, a new value for the "circles-production-mainnet-privateKey" local storage variable is assigned a new and different value each time you log out.
Is it necessary that that value is there? Why is it a different one each time?

**Comment by louilinn** [comment]
As soon as you enter circles.garden the key is generated. It's the same when you log out. It exists to prepare for signup. You could change the logic to do it later but it isn't a problem besides maybe confusing for someone looking in the storage. Redux generates a state when it doesn't find any key already existing. There is always a key ready for you to start sign up.

**Comment by llunaCreixent** [comment]
The confusion is solved then, thanks!!
