### ISSUE TITLE
Entering seedphrase and obtaining another wallet that is not deployed

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#275]
Actually the user didn't use the seedphrase they got in the onboarding process (this seedphrase is lost), they used the seedphrase they exported from the app. The issue is that the action that preceded the export of the seedphrase was the creation of a shared wallet, which failed for some reason and is owned by a new different owner than the original individual account.
We should check why this happened in the Creation of a shared wallet process. Is there any moment when a new private key or owner account is created?

**Comment by llunaCreixent** [comment]
We should also check what happens when the creation of a shared wallet fails. Do the values on local storage change?

**Comment by triaslucia** [comment]
Check if this is still an issue

**Comment by triaslucia** [comment]
Not expected to affect a lot of users

**Comment by louilinn** [comment]
This hasn't affected more users, will put as not planned
Cannot reproduce.
