### ISSUE TITLE
[#266-Re-design of Shared Wallets Creation process] - Add background, profile picture 

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#276]

**Comment by mikozet** [comment]
Hi @triaslucia,

It looks like we have two version of new gradient background. One is oval the other one is circular.
We might have both of them but I am just thinking maybe it would be worth to have just one of it?
![Zrzut ekranu 2021-12-20 o 21 50 18](https://user-images.githubusercontent.com/95082155/146831154-9aed16fc-bb11-47f1-9768-565b7992bb45.png)
![Zrzut ekranu 2021-12-20 o 21 50 02](https://user-images.githubusercontent.com/95082155/146831159-d9ee78d6-eab2-4534-bcad-f02cef0ecac4.png)

**Comment by mikozet** [comment]
Also it looks like gradient has slightly different color for mobile and tablet... Maybe it would be good to stick with one version? For tablet it seems to be: `background: linear-gradient(180deg, #FF8E00 0%, #D12D5F 51.56%);` For mobile I cannot read value from figma unfortunately.. 
![Zrzut ekranu 2021-12-20 o 21 59 46](https://user-images.githubusercontent.com/95082155/146832152-58391de7-8782-4be9-8de4-c811ca24dced.png)
![Zrzut ekranu 2021-12-20 o 21 59 42](https://user-images.githubusercontent.com/95082155/146832156-ee53fc64-8d6e-4f9b-81c7-fec4dcdb57e9.png)
![Zrzut ekranu 2021-12-20 o 21 59 31](https://user-images.githubusercontent.com/95082155/146832159-9cb50b57-6df6-4073-8300-986a20d9cf52.png)

**Comment by triaslucia** [comment]
I just adjust the on-boarding of the Wallet to the rest. As the on Boarding was the onl one different. 
We stick to "Circular one" 

About the gradient, yes the idea is to stick to one. I'm not sure why you see it different, I check the file and it is all the same. 
You can find it in the color library of the figma file, and just stick to it. 

Name: Gradient/Sun
