### ISSUE TITLE
[#266-Re-design of Shared Wallets Creation process] - dashboard page

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#283]
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A18052
![Zrzut ekranu 2022-01-14 o 15 44 39](https://user-images.githubusercontent.com/95082155/149534178-a7018fcb-fa11-4c2f-b6b7-9c5a0870d6f1.png)

**Comment by mikozet** [comment]
Hi @triaslucia,
![Zrzut ekranu 2022-01-19 o 14 16 12](https://user-images.githubusercontent.com/95082155/150138230-65728461-23e0-44d8-8f28-055d5db62ab7.png)
1. Could you elaborate about which profile pics users with name should we display here - are these users randomly choosen? Or these are persons we trusted - (if yes what should we display once user doesn't have any users there?
2. What happens when user clicks 'Send Circles' button ? Does he goes to https://circles.garden/send page or it acts like a tab and we display some content instead of profile pics?

**Comment by triaslucia** [comment]
1_This is not par of the redesign to be honest. Which pictures are gonna be displayed remains the way it is done.  I cannot tell exactelly how it is made now, but most of the times you see people with who you interacted at last -both turst and exchange wise. 

2_ Yes, exactelly. And the screen of send remains the way it is now.

**Comment by triaslucia** [comment]
2_ yes exactelly. And the screen of send remains the way it is now.

**Comment by mikozet** [comment]
![Zrzut ekranu 2022-01-25 o 12 56 23](https://user-images.githubusercontent.com/95082155/150972752-4cd53628-18b4-4a14-8ad4-6ae96514dce5.png)
Basically we display the same list as here at the image
Trust buttons links to trust page, send circle button links to send circles page
