### ISSUE TITLE
Creation of a SW success but not in the app

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#289]
Maybe is because it asks the graph for info that is not ready yet?

**Comment by louilinn** [comment]
When the graph is slow to confirm the creation of a SW or a transaction

Three steps:
1. transaction is sent to blockchain
2. transaction is confirmed (feedback to user)
3. transaction is available in the graph (what shows up in the 

Between step 2 and 3 the user might be confused

The unconfiremed (from graph) data but confirmed by BC transaction can be cached in the broweser so it doesnt create this delay /confusion

**Comment by triaslucia** [comment]
This one can be closed, right?
