### ISSUE TITLE
List of shared wallets cannot be scrolled

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#303]
**Describe the bug**
In the account switching view https://circles.garden/profile there is no scroll if you have created more shared wallets than can be displayed on the screen. Only solution for the user to reach their bottom accounts is to zoom out which is neither clear nor UX friendly.

**To Reproduce**
1. Go to https://circles.garden/profile
2. If you have many shared wallets (more than 8?) you will notice you cannot scroll to access them all
3. Scrolling works if you have few wallets

I have not reproduced this error but we should try to do it locally (without spamming production with many new SWs)
Martin experienced this bug in mid January 2022 on desktop

**Comment by triaslucia** [comment]
I also received info on this bag. 
More people experience it still now on **mobile**.

Here a screenshot: 
![Screenshot_20220412_120459_com android chrome](https://user-images.githubusercontent.com/38475134/163153001-516aefcd-b5bf-435a-a1db-10365d435ce1.jpg)
