### ISSUE TITLE
Not getting UBI payments?

### ISSUE THREAD

**Issue by stevietrouble** [CirclesUBI/circles-myxogastria#304]
**Describe the bug**
My friends and I haven't gotten a UBI payment in like 6 months. Is something broken on our end? Did we need to fill up some Gnosis wallet? We're running our own circular economy here just to test out the product.

https://circles.garden/profile/0x4CE43E05D7e38209338d750f4f4f1211d1F2ddaE

**To Reproduce**
1. Go to transaction list
2. No UBI payments since 2021-06-26

**Expected behavior**
Regular UBI payments to everyone in our trust group.

**Screenshots**
![Screenshot_20220206-103803](https://user-images.githubusercontent.com/605676/152696164-177e14db-7e6c-48bb-8ee3-768a9aeb70a1.png)

**Desktop-Computer (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android Q
 - Browser: Chrome
 - Version: Latest as of today

**Additional context**
We set up our own here by sending xDai to certain addresses because we wanted to try it out.

I'm a professional web developer, lmk if you need more info e.g. cookies, dumps, netlogs, etc.

**Comment by louilinn** [comment]
@steventrouble You did not log in to your account June 26th 2022 and October 34th 2021 (or even February 2022) which is more than 3 months. When you don't log in for 3 months, your UBI is not collected and your account gets locked (forever). This is called the dead man's switch. In the new contracts update to circles 2.0 next year this will be removed. This functionality has been badly communicated and we are sorry about this.

When your account gets locked it remains and can still be used for transitive transfers between accounts but it will no longer generate UBI.I suggest to create a new account and make sure to log in once every 3 months minimum.
