### ISSUE TITLE
shared wallet profile frame is too big 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#327]
There frame on Shared Wallets profile picture are now too big. And they appear floating over other elements. 
<img width="253" alt="Screenshot 2022-04-05 at 14 28 45" src="https://user-images.githubusercontent.com/38475134/161955079-072c9daf-584e-4504-baa6-38a6db488b3a.png">

**Comment by mikozet** [comment]
this task has been fixed here so I am closing it
https://github.com/CirclesUBI/circles-myxogastria/pull/330#pullrequestreview-971915620

**Comment by mikozet** [comment]
closing as we have new task for it:
https://github.com/CirclesUBI/circles-myxogastria/issues/344
