### ISSUE TITLE
alert shows incorrectly (in dashboard and signup) - it is too limited in space and hidden behind balance 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#328]
The Alert msg box, appears incomplete, sort of like hidden by a white box. The icon of Alert is on top and visible. 
<img width="615" alt="Screenshot 2022-04-06 at 12 30 58" src="https://user-images.githubusercontent.com/38475134/161955720-560af11a-6fbc-44b4-939f-f81e9baee87a.png">

**Comment by mikozet** [comment]
Hi @triaslucia, 
I am not sure how to replicate this... . Could you share a link and steps to reproduce please? Also type of device..
