### ISSUE TITLE
Separate menu for individual wallet (has shared wallet menu currently) 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#329]
The Menu for individual wallets and Shared wallets have different colors but as well different entries. As Shared Wallets has the entry for the Add Members screen. 

- The menu on Desktop version is to large. We need to adjust dimension. 

**Design Material**  https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=5583%3A10662

**Comment by mikozet** [comment]
Closing as this is solved now and merged
