### ISSUE TITLE
Fix step navigation in onboarding including color gradient

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#335]
the lines should be behind the circles
circles should follow organization gradiant color theme
size changes: dimensions of circles and the text size
@triaslucia updates the design and links here

- [x] name on steps
- [x] stepper component desig
- [x] mapping to the steps in each view
- [x] updates margin top for stepper so it is consistent on stepper steps with avatar and without
- [x] change color of header icon in Validation screen for white

![Screenshot from 2022-05-18 12-06-25](https://user-images.githubusercontent.com/20553836/169014653-e1ff0eaa-3e60-4163-872c-26c07be5b357.png)

**Comment by triaslucia** [comment]
This is ready @mikozet 

Design Material: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4356%3A56488

You can find the Icons both Individual wallets and Shared wallets and as well the different sizes for Mobile and Desktop. 
You can as well fin the entire behaivour of the "Step navigation"  screen-by-screen for both Wallets.

**Comment by louilinn** [comment]
Related: make sure this is fixed: https://github.com/CirclesUBI/circles-myxogastria/issues/345

**Comment by mikozet** [comment]
Hi @triaslucia ,
I have problems with these gradients. Basically they don't look great once we use them in the app.
It is difficult to override it and also some elements kind of don't accept those values and appear blank (like lines connecting dots).

Are we able to do something here with it? Like use maybe similar gradient as before (in terms of generated code with different values)?
Here is generated code for the previous one:
`linear-gradient(#48B2B7, #06FC9D) padding-box, linear-gradient(to bottom, #48B2B7, #06FC9D) border-box`

Also thing to consider would be if we need gradient here as the new one will be barely seen to be honest even if somehow we make it working..


I attach how it looks like at the moment..
![Zrzut ekranu 2022-06-16 o 10 52 19](https://user-images.githubusercontent.com/95082155/174033291-305a014c-2864-431b-aabd-3e27d41035e5.png)
![Zrzut ekranu 2022-06-16 o 10 52 51](https://user-images.githubusercontent.com/95082155/174033297-adf82a34-cad7-4fe3-b20e-52a9649c3f22.png)

![Zrzut ekranu 2022-06-16 o 10 51 53](https://user-images.githubusercontent.com/95082155/174033285-3866684a-ac08-4450-a864-c73172a2afd4.png)
 
![Zrzut ekranu 2022-06-16 o 11 03 14](https://user-images.githubusercontent.com/95082155/174034669-f99b9a52-a8a4-4f85-8955-99c464dc5e5d.png)

**Comment by mikozet** [comment]
I added those two in checkpoints list in description:
- updates margin top for stepper so it is consistent on stepper steps with avatar and without
- change color of header icon in Validation screen for white
