### ISSUE TITLE
Header icons should be white for both flows - normal and organisation 

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#343]

**Comment by louilinn** [comment]
I noticed after we merged the PR #359 that all icons become white in the whole app meaning they are not visible on all the white headers. This needs to be fixed. 
- [x] make icons white in onboarding and dashboard
- [ ] restore black icons on other views

**Comment by louilinn** [comment]
Problem arose: https://github.com/CirclesUBI/circles-myxogastria/issues/379 but this issue is done
