### ISSUE TITLE
Map steps to correct screens on create user account flow

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#345]

**Comment by triaslucia** [comment]
@mikozet  thi si ready! 

Material: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A18052

0.Onboarding: 
<img width="830" alt="Screenshot 2022-05-19 at 18 30 29" src="https://user-images.githubusercontent.com/38475134/169351397-6d2bcca9-ea6c-4494-aa30-da5148beb5db.png">

1.Create Wallet
<img width="296" alt="Screenshot 2022-05-19 at 18 32 17" src="https://user-images.githubusercontent.com/38475134/169351719-807791f2-b161-4b56-a4e9-b159293874af.png">

2.Fund Wallet

<img width="571" alt="Screenshot 2022-05-19 at 18 32 49" src="https://user-images.githubusercontent.com/38475134/169351818-41f7ceaf-edfb-4010-a670-82c9fe676f3a.png">

3. Custom Wallet
<img width="694" alt="Screenshot 2022-05-19 at 18 36 57" src="https://user-images.githubusercontent.com/38475134/169352614-751c36d4-f645-4db1-99e9-3a904e07c349.png">

for “add photo” you first have only the button of "I'll do this later". If the person chooses  a picture this button changes to "Next"
