### ISSUE TITLE
On Onboard organisation 'Sign me up' text btn should be last one. 

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#346]
In between screens the button text is 'Submit'

- [x] fix text on buttons in order
- [x] change text depending on if photo is uploaded or not

**Comment by triaslucia** [comment]
@mikozet this is ready!

<img width="637" alt="Screenshot 2022-05-19 at 17 52 34" src="https://user-images.githubusercontent.com/38475134/169343758-2765095c-8987-42f2-82fa-03c23d543239.png">

**Comment by triaslucia** [comment]
Here is the design material: 

https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A26250

**Comment by louilinn** [comment]
Small fix

**Comment by louilinn** [comment]
@triaslucia the text is fixed but changing the button based on if a photo is uploaded instead of just disabling is more tricky. Can we deprioritize it or is it important that I'll do this later doesnt show together with continue buttton?

**Comment by triaslucia** [comment]
I understand, let try to keep it as simple as possible @louilinn
Lets keep the design with 2 buttons, and just have the "Next" button deactivated on the first screen, and activated after uploading the profile picture.  I this possible? 
<img width="491" alt="Screenshot 2022-06-13 at 15 11 06" src="https://user-images.githubusercontent.com/38475134/173361392-89cd6291-26cc-4694-8f19-1c79ab9cbac3.png">

Figma file is already updated!

**Comment by mikozet** [comment]
Hi @triaslucia I moved your above comment to separate task:
https://github.com/CirclesUBI/circles-myxogastria/issues/392
