### ISSUE TITLE
Once scrolling BackgroundCurved background should dissapear and new header bar should appear

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#349]
@triaslucia could you add turquise version of it in design

**Comment by triaslucia** [comment]
@mikozet this is ready! 

Here you can find both design Individual wallets and Shared Wallets for both version desktop and mobile. 

Link: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4356%3A49547
