### ISSUE TITLE
App Notifications about system transition 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#360]
For preparing the transition smooth we will display a set of notification in the coming weeks. 

Schedule: 
**#1: 30st of May**
explain there is gonna be a big system change ( we are combining App lunching, web lunching and system transition. So people will get it us a global system change)
**#2: 8th of June**
Issuance rate of the Circles UBI .
**#3: 15th of June**
Specific information about the App. No possibility of not transition to the new system.
<img width="1081" alt="Screenshot 2022-05-27 at 09 46 23" src="https://user-images.githubusercontent.com/38475134/170655492-b02ec5fe-5d83-4cb9-84af-3955efdc6b4d.png">

Design Material: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=5878%3A10181
Hyperlink "Read more": https://circlesubi.medium.com/the-revaluation-of-the-circles-system-c6eea70e767d

**Comment by mikozet** [comment]
Hi @triaslucia few questions here:
Should we have some kind of x icon to close those or we would rather prefer to display it all the time?
Should we display it everytime user refreshes dashboard page or once he closes it (if it is possible) we shouldn't display it anymore.
What should we do for users who log in at 8th of June and not at 30th of May - should we display both messages below each other?

**Comment by triaslucia** [comment]
@mikozet  No , no no need to have the cross and so...this is supposed to be the simple "alarm" display we already use normally. Just with the color change so people realizes that are 3 different msg! 

about the dates, we agree on our meeting on just displaying one after the other. Each of them during a certain amount of time. Priority is that the first msg should be out today!  

In case of account which are open the first time after the 8th if June, we could display both msg- but what do you need from me? 
We have to follow the common communication plan we are using in all channels, the App is already delayed.

**Comment by mikozet** [comment]
@triaslucia it is ok, we missed the link but now I can see it in design.

**Comment by mikozet** [comment]
Updated with changes in design: 
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A26250

**Comment by louilinn** [comment]
Should we not have any explicit mention of balance change in the last box?

**Comment by mikozet** [comment]
Hi @triaslucia do we have final design for tomorrows update? It looks like it is missing...
![Zrzut ekranu 2022-06-14 o 09 50 48](https://user-images.githubusercontent.com/95082155/173523393-9f610c3c-21ec-4769-b896-790947968d69.png)

**Comment by triaslucia** [comment]
@mikozet ready to pick up! 

<img width="310" alt="Screenshot 2022-06-14 at 12 17 26" src="https://user-images.githubusercontent.com/38475134/173554973-01d4c022-8627-4c66-92d1-c81eeac59018.png">

Material: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4356%3A49547

**Comment by louilinn** [comment]
We talked about keeping a box after the transition with a link to the article (since you cant find it in the app after you close the transition screens)
I have assumed we are still doing that?

You can see my text changes here:
https://github.com/CirclesUBI/circles-myxogastria/pull/412/files

Reference issue created in relation to that discussion:
https://github.com/CirclesUBI/circles-myxogastria/issues/350

**Comment by triaslucia** [comment]
I do not remember this... Actually the entire idea of the "Transitions screens" is to avoid the box alert. After the change I do not want to have a box.  I want people to have their new wallet as clean as possible to learn how to use it. If we add this box it disturb the learning process of the new interface.
