### ISSUE TITLE
Broken Floating Navigation in Organization wallet - Add members link.

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#380]
Floating Navigation doesn't cover opening button correctl
![Zrzut ekranu 2022-06-10 o 11 31 11](https://user-images.githubusercontent.com/95082155/173036900-fada3dd8-cbfb-4ba2-90cc-5d3800dcdb1c.png)
y

**Comment by louilinn** [comment]
Also remove Edit profile link from both menus temporarily (comment out)
