### ISSUE TITLE
Delay between transaction and UI feedback (notification, button states etc.)

### ISSUE THREAD

**Issue by samuelandert** [CirclesUBI/circles-myxogastria#39]
I use to have a very long delay when I send circles between the successful notification and the account balance showing the updated value.

**Comment by adzialocha** [comment]
We're currently getting most of our data from The Graph as an caching layer sitting between the blockchain and the client. So right now we are waiting for:

1. Mining the block
2. The Graph storing the new state
3. App polling the next update from The Graph

... which can be a few seconds per point in worst case.

I wonder if there are ways to improve the experience by not using the graph but query the chain directly for certain events / states like the balance. The good part about using the graph is that it gives us the balances of all tokens we own per account, so we only need to summarize and display them to the user, whereas querying the contracts would require more work.

**Comment by adzialocha** [comment]
We're experiencing an similar UX issue with trust transactions: Users trust / untrust someone and the UI is still showing the last state without any changes. This makes sense from the technical perspective, but confuses the user and makes them click twice.

**Comment by adzialocha** [comment]
Users clicking twice can cause the transactions to be part of the same block, resulting in a nonce duplicate and Relayer error:

https://github.com/gnosis/safe-relay-service/blob/master/safe_relay_service/relay/services/transaction_service.py#L352
