### ISSUE TITLE
Transition screens to New Wallet

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#390]
We want to support the transition in between Apps for people not to abruptly find a totally new Wallet without advice. 
We will display a set of 3 screens for the first time wallets Login after transition. 

- We use the On-boarding slides system 
- It displays only the first time a Wallet is opens after the transition
-After clicking "Move Forward" people should be re-directed to the landing page of the wallet.
-It is not skip able
-The X icon leads to Login page again. 

<img width="1043" alt="Screenshot 2022-06-15 at 12 32 00" src="https://user-images.githubusercontent.com/38475134/173810035-311a35fd-3f34-48e3-b19d-5a9df9ee7530.png">

**Design Material**  
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4356%3A49547

**Comment by louilinn** [comment]
Should w have the exit cross? where would it take you?

Also should there be something on balance change here?

@triaslucia

**Comment by triaslucia** [comment]
@louilinn 

About the X icon or "exit Cross" as Explained in the Issue it leads you to Login Screen again. Its necessary yes. If not the process its too blocked. 

About Balance, good point. I include it now on the first slide. The same msg we got now displayed. 

Material: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4356%3A49547

**Comment by mikozet** [comment]
Hi @triaslucia 
I have concerns about consistency. In our trial for onboarding we have skip button as well as previous button...

Shouldn't we have it here as well?
![Zrzut ekranu 2022-06-22 o 10 07 26](https://user-images.githubusercontent.com/95082155/174978680-ca2bb20a-9441-46df-9f30-ce3600aeaf89.png)
![Zrzut ekranu 2022-06-22 o 10 07 44](https://user-images.githubusercontent.com/95082155/174978693-e9b03d5c-9399-4b25-b16a-ad55be42609f.png)

**Comment by mikozet** [comment]
@triaslucia  Also one more:

Should we have a gradient on the curve or not? As it looks like on mobile we have gradient but desktop we don't which I believe is probably mistake..
We should have probably same solution (regarding gradient) in Transition tutorial as well as Onboarding tutorial..
![Zrzut ekranu 2022-06-22 o 10 15 25](https://user-images.githubusercontent.com/95082155/174979361-ddbbfc8f-72b6-4e5a-86b2-039f59368d86.png)

**Comment by triaslucia** [comment]
@mikozet 

About consistency its not the same on-boarding and transition - so differences are needed. Also this Transition slides are gonna be displayed only once in peoples life, so there is not even time for them to biuld up a necessity of consistency. Don't worry much about this. 

- Skip button should not be at transition screens there because we do not want people to be able to skip this -unfortunately! We need people to reach the last transition slide to understand that a new Wallet interface is coming. 
- Previous button vs X button: We can add the previous button in the second and third slide, if you think is needed. Personally I think this process should be as less interactive and one direction, because it is actually a very blocked process. People cannot choose if they want to do it or not. So should not give fake expectations. 

- Gradient: In the Figma file, all has the same gradient. ( Also because I copy paste the screen and change the content. So non change should be there. ) The background is a gradient, but its very subtle, slightly seen. Also I see same gradient both on mobile and on desktop. So all good as it is on the Figma file. 
<img width="809" alt="Screenshot 2022-06-22 at 11 00 14" src="https://user-images.githubusercontent.com/38475134/174990095-fe245b07-af86-4ca5-9ece-824e30decf69.png">
<img width="1176" alt="Screenshot 2022-06-22 at 10 59 42" src="https://user-images.githubusercontent.com/38475134/174990110-c47a6e67-c844-4bd8-aff3-a080608de420.png">

**Comment by mikozet** [comment]
Thank you for clarification 👍

**Comment by louilinn** [comment]
@triaslucia if it shouldnt be skipable, why have the X at all?
I also this it makes sense to be able to go back and read if you are confused, annoying if you click to fast and then the information is gone forever. (This happened to me while testing :sweat_smile: )

As for the content on the second slide. I would maybe make it clearer that the amount will deacy over time. At the moment it sounds a bit like the demurrage is the reason why your balance triples (when the demmurrage will make your balance decrease and it is the new Circles value that will triple the budget)
Up to you of course but I see room for improvement in the information. If you want I can write a suggestion.

**Comment by louilinn** [comment]
Suggestion for Slide 2:

The increase in your daily UBI will also work retroactively and make your balance increase based on the amount of time you've spent at Circles. If you were holding 50 CRC you will now see around 150 CRC. Basically, your balance will tripple.

Another change is that we are now displaying balances with a demurrage or decay rate of CRC of 7% per year. This means that the Circles you don't use will decay over time. If you passively hold onto a lot of Circles (like a fortune of CRC), your balance may decrease over time if the decay is larger than your UBI. 

Shared wallets will notice the decay by a slow decrease in the balance over time.

**Comment by louilinn** [comment]
Shorter suggestion:

The increase in your daily UBI will also work retroactively and make your balance increase based on the amount of time you've spent at Circles. If you were holding 50 CRC you will now see around 150 CRC. Basically, your balance will tripple.

Another change is that we are now displaying balances with a demurrage or decay rate.
Read more here

**Comment by triaslucia** [comment]
@louilinn I just edited the figma file. You'll find in there the last version according to your suggestion. 

https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4356%3A49547
