### ISSUE TITLE
Development: console log errors due to a merged commit

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#391]
this commit https://github.com/CirclesUBI/circles-myxogastria/commit/9f0f9857b91acc67ff106c561a70806454b8c7eb
has broken a lot of views in myxo development with the following error:

Material-UI: The key confirmButton provided to the classes prop is not implemented in ForwardRef(Dialog).
You can only override one of the following: root,scrollPaper,scrollBody,container,paper,paperScrollPaper,paperScrollBody,paperWidthFalse,paperWidthXs,paperWidthSm,paperWidthMd,paperWidthLg,paperWidthXl,paperFullWidth,paperFullScreen.
at WithStyles (http://localhost:8080/lib.js:155503:31)
at DialogPurple (http://localhost:8080/app.js:13284:23)

**Comment by mikozet** [comment]
I removed few others console warnings:
 
![Zrzut ekranu 2022-06-14 o 15 28 26](https://user-images.githubusercontent.com/95082155/174012440-44a37f07-1b3f-4960-a28d-70a097987c80.png)

![Zrzut ekranu 2022-06-14 o 15 28 01](https://user-images.githubusercontent.com/95082155/174012444-9b3d11e4-49a5-4662-a9d3-047275638b53.png)

![Zrzut ekranu 2022-06-14 o 16 04 05](https://user-images.githubusercontent.com/95082155/174012423-0ba532af-5cd3-46ca-bc68-af1af8a1e69e.png)
from: https://github.com/CirclesUBI/circles-myxogastria/pull/366

![Zrzut ekranu 2022-06-14 o 15 37 39](https://user-images.githubusercontent.com/95082155/174012428-32588d25-7c1a-411d-8dc6-5578b1194069.png)
