### ISSUE TITLE
Add a 'Next' button on upload image screen

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#392]
Lets keep the design with 2 buttons, and just have the "Next" button deactivated on the first screen, and activated after uploading the profile picture. I this possible
![](https://user-images.githubusercontent.com/38475134/173361392-89cd6291-26cc-4694-8f19-1c79ab9cbac3.png)
?

**Comment by louilinn** [comment]
this is the state in development currently (same for Shared Wallets)
![Screenshot from 2022-06-17 16-49-25](https://user-images.githubusercontent.com/20553836/174322454-e2eb8005-88b3-4a05-945a-b1ccc324e255.png)

I did that fix requested here https://github.com/CirclesUBI/circles-myxogastria/issues/346  was easier than I thought
So we can close this?

**Comment by mikozet** [comment]
Hi @louilinn,
It is another request from Lucia. Have a look into last comment here:
https://github.com/CirclesUBI/circles-myxogastria/issues/346

I added `Next` button with disabled state and there is also `I'll do this later` button

**Comment by louilinn** [comment]
Hi Miko, but this request from Lucia was only if the first request was not possible. 
And the first request is already implemented. So the second request is thus not relevant.
