### ISSUE TITLE
Implement a "News" menu on the Activity Log screen:

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#396]
**We do not count with a direct way to communicate with our Wallet users**
Whenever a problem occurred, we are doing maintenance, or we are lunching something new, we do not have a direct way to communicate with our Wallet's users. WE have to communicate it per email , Social Media, etc. 
If we can reach people through the wallets, we easy the communication, we can as well make the aware when our infrastructure might crashed for maintenance so they are aware in advance. 

**Add a _Updates_ menu on the Activity Log screen.**
We will add a menu on the Activity Log screen, in which people will received written notification from our side. We will use this to communicate all issues related to the Wallet. 

**Design Material** https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A26250

**Comment by louilinn** [comment]
Ignore, the mention. I linked the wrong issue above

**Comment by louilinn** [comment]
@triaslucia Some questions and comments

1. how do you want to add these messages? We were thinking to add some kind of simply admin interface or something. it is also possible to manually add entries to the database but it is not maybe viable long term
We can add notifications in advance, like scheduling them, either way.

We will store
- messages in all languages that the app supports (currently only english)
- date of notification
- specification of which icon (icon id)

2. As for the icons, will it only be these three icons? I think we should add them all and then those are the choices for new notifications.

3. These messages will all be general right? And the same for all users?

4. We should probably define a max message length too

**Comment by triaslucia** [comment]
1. I do not have an answer to this, but waiting for your input in these. My idea was that the main communication should be between you and the user, so you will do it. The msg the COOP will send in here should be very limited, so my idea was to plan them in advance and ask you to implement them. Would this be possible? For me would as well be possible to do it by my self if you teach me how. 

2. Yes so far would be only 3. The idea is to keep it as simple as possible, and test it correctly. We should be careful with how much maintenance work this feature needs, before adding complexity on the design. We have 3 msg categories, ergo we have 3 icons. Its enough for the beginning. 

3. Yes all general and equal. In a future, with the group currencies, we could think of having the option of communities overtaking this feature and communicate stuff only inside their communities. For this the Admin interface might be needed. But then we have to evaluate how this things are gonna work, who has the right of it and so on...its a big topic to open to discussion as it might create different profiles with different rights, so its a political question. 

4. Yes! Like we have for notifications

**Comment by triaslucia** [comment]
Design Phase of this is done. Ready for implementation! 
All material needed is  here. Components, with different states. As well as the final version of our Welcoming msg. 

*Design Material* https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A26250

**Comment by louilinn** [comment]
@triaslucia I am wondering if we are going to have different items in the different logs?
I would have assumed to replace the activity container when we implement news feed?
@mikozet 

![Screenshot from 2023-02-10 17-15-24](https://user-images.githubusercontent.com/20553836/218141402-51251360-7fde-48e1-8007-5fc807b8c7dc.png)
![Screenshot from 2023-02-10 17-13-45](https://user-images.githubusercontent.com/20553836/218141406-684527b6-fdd7-4c9d-9732-ef724c948716.png)
