### ISSUE TITLE
Feature: Separate notifications into several filtered views

### ISSUE THREAD

**Issue by samuelandert** [CirclesUBI/circles-myxogastria#41]
I somehow miss a filtered list view of my IN and OUT circle transactions in generell on my own user and between a user and me when I click on the user.

**Comment by adzialocha** [comment]
We were wondering if it makes sense to actually separate notifications into multiple views based on their type and context and skip filtering:

1. Transaction activity with only in / outs of Circles concerning your account in the current notification view (can be easily displayed with (+50 Circles, -10,50 Circles as seen in banking apps)
2. Safe owner management / device adding, removal activity in the Device management view
3. Trust / untrust activity in your profile or other profiles view

**Comment by samuelandert** [comment]
Yes totally, that was my intent as well, was just thinking of doing it step after step.
