### ISSUE TITLE
Re-design of the Validation process  

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#417]
We are gonna displayed the profile info of each trust connection a wallet gets during validation process. 

**Design Material** https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A42078

**Comment by louilinn** [comment]
https://github.com/CirclesUBI/circles-core/issues/124

**Comment by louilinn** [comment]
Duplicate of this https://github.com/CirclesUBI/circles-myxogastria/issues/325
