### ISSUE TITLE
UBI notification of timeCircles increases

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#454]
I received my UBI this morning, and right after seeing the pop up (29.7560 circles), I see in the activity log that the amount is 29.76.
Everything makes sense until now. But then, 2 minutes after I go to the activity log and see that it says 29.79 circles.
Also, my UBI from yesterday changed from 17.00 to 17.01 circles.
However, I don't see those changes for the manual transfers I've made.

**Comment by llunaCreixent** [comment]
I looks like it's the time difference between the moment when the user interacts and the date registered in the subgraph (blockchain tx).

**Comment by llunaCreixent** [comment]
One possibility could be to show in the popup the value ~5 sec after.

**Comment by llunaCreixent** [comment]
One possibility could be to show in the pop up  the value on ~5 sec later (when the tx will potentially be written in the blockchain)

**Comment by louilinn** [comment]
@mikozet is it correct that this issue is also related to wallet-wallet transfers and their notifications or should we add a seperate issue?

**Comment by mikozet** [comment]
@louilinn It is related, it may happend that I will fix both or first at once - so maybe let's wait till tomorrow with creation new issue. Currently I am working on notification of receiving circles once they happend between two users account

**Comment by louilinn** [comment]
We found the bug of received notifications, PR coming. UBI notifications remain. They are different bugs.

**Comment by louilinn** [comment]
I have been trying to reproduce this error unsuccessfully. I suspect it has been resolved by some other fix.

|Date |UBI notification popup  |Balance diff instant |Activity log instant |Activity log minutes after |Activity log days after |
|---|---|---|---|---|---|
|14/3 |119.3677   |17831.06->17950.43 => 119.37  |119.37   |119.37   |---   |
|09/3 |4.3893 |177807.68->??? |40.39 |40.39 |40.39 (5 days)|
|07/3 |28.7094   |17784.71->17813.43 => 28.71  |28.71   | --- |28.71 (6 days) |
|06/3 |136.5300  |17652.26->???   |136.53   |---   |136.53 (7 days)  |

Closing issue
