### ISSUE TITLE
Improve basic navigation UX

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#46]
Currently the navigation handling (going into and out of views, going backwards) feels confusing. We're choosing to have same button positions for different actions (first you click in the upper left corner for entering a view and then again to leave it ..).

**Comment by samuelandert** [comment]
I made a quick navigation mockup, what do you think about this? 
![circles-mockup](https://user-images.githubusercontent.com/747161/82901048-ad826400-9f5d-11ea-9b18-d4644a26fb6b.png)

**Comment by adzialocha** [comment]
@saraswathi what do you think?
