### ISSUE TITLE
Refactoring Input Components

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#464]
**Refactoring Input Components**

We should substitute all Input components. 

We should particularly for Error-Input state work on specific changes. 

Design Material: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=6783%3A10747

**Comment by mikozet** [comment]
We also agreed to remove 'ok' Icon from the Input

**Comment by louilinn** [comment]
Were should these be used? In Send view as well? Search?

**Comment by ruchajoshi08** [comment]
these are to be used in the onboarding flow and edit profile screen. https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=6783%3A10747

**Comment by louilinn** [comment]
Confirming here: @ruchajoshi08 @triaslucia 
![Screenshot from 2022-11-17 12-03-21](https://user-images.githubusercontent.com/20553836/202429777-150e9efb-a14e-4a7d-b56a-a915607ba93b.png)
We use the new input field in search, and keep old input field in transfer amount and message?

**Comment by ruchajoshi08** [comment]
yes, that input element will be different. we have not got to refactor the screen elements on Send circles. Will create a new ticket for it.


Quick question - can we continue to have the search icon on the right side like we do in the current design?

**Comment by mikozet** [comment]
from meeting with Lucia: 
Text in Username input field for personal wallet, text below is incorrect - should not be friend - see update in figma
Right now input instructions are in error message and the position is wonky for long error messages. (see invalid chars for username for example)
Change the input errors and the instructions go below, see figma
