### ISSUE TITLE
Repeat pathfinder request with lower amount when timeout reached

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#469]
Given the complexity of the capacity network around some accounts, the pathfinder needs more than 60 seconds, which is the current timeuot configured to deliver a response. Therefore, after 60 seconds, if the pathfinder hasn't found a solution, the api responds 0.
We could also try to repeat the query with a lower amount so as to help the pathfinder to find a solution faster.

See circles-myxogastria/src/utils/findPath.js

**Comment by llunaCreixent** [comment]
Related https://github.com/CirclesUBI/circles-api/issues/81

**Comment by louilinn** [comment]
No longer necessary
