### ISSUE TITLE
"Not connected to internet" error and can't transfer my seed phrase

### ISSUE THREAD

**Issue by GriffGreen** [CirclesUBI/circles-myxogastria#47]
![photo_2020-05-26_15-56-42](https://user-images.githubusercontent.com/14945613/82909403-87fb5780-9f69-11ea-99fc-1d832dd1cd2f.jpg)

Getting that on the phone... i couldn't get passed getting my 3 trusted connections so i tried to move it to the desktop but when i use the seed phrase... i can't restore it

<img width="832" alt="Screen Shot 2020-05-26 at 3 59 18 PM" src="https://user-images.githubusercontent.com/14945613/82909713-eaecee80-9f69-11ea-8d50-eb22af5c04df.png">

Here is my invite text... which is prob a second bug cause i get the same link twice? 

Hey! Check out my profile at: https://circles.garden/profile/0x39f5d0291181a44F309493abd46eb48268899808 https://circles.garden/profile/0x39f5d0291181a44F309493abd46eb48268899808

I'm using chrome on a galaxy s10+ android and then trying to move it to chrome on a 2014 macbook

**Comment by adzialocha** [comment]
The connection error could be related to this issue: https://github.com/CirclesUBI/circles-baby-phoenix/issues/30. Did the problem disappear after reloading the page?

**Comment by adzialocha** [comment]
> Getting that on the phone... i couldn't get passed getting my 3 trusted connections so i tried to move it to the desktop but when i use the seed phrase... i can't restore it

Technically we are not capable of doing so right now, see here: https://github.com/CirclesUBI/circles-baby-phoenix/issues/23
