### ISSUE TITLE
Refactoring Trust connections buttons

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#477]
updating all trust connection buttons. 

**Design Material** https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7301%3A18288

**Comment by louilinn** [comment]
@triaslucia should all round buttons have this shape?
I know this issue concerns trust buttons alone atm but for the entire refactoring I guess all round buttons should look similar? Such as the send button and three dots menu?

**Comment by louilinn** [comment]
Rucha: " yes all circular buttons in the end should look like this wobbly shape. " @mikozet

**Comment by triaslucia** [comment]
yes! as clarify by Rucha, they will all have this handwritten style.

**Comment by louilinn** [comment]
Update: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7301%3A18288
Now for cases / combinations of color and icon
Change is for when someone else trust you but you don't trust them.

Implemented so far: This button is pink with + icon
Change: Should be purple with + icon

@mikozet @louilinn
