### ISSUE TITLE
Refactoring send circles icon

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#478]
Update send circles icon.

Design Material https: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7302%3A18656

**Comment by louilinn** [comment]
Send Icon exists also on Profile mini, in mutual connections and in Search list
![Screenshot from 2022-10-14 15-44-50](https://user-images.githubusercontent.com/20553836/195862132-ce488172-3f45-41b1-bdd4-1e7caab0f6f5.png)

**Comment by louilinn** [comment]
Design update needed

**Comment by ruchajoshi08** [comment]
Unable to assign me to this. Can't edit. I have added the replacement icon to the figma file https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7302%3A18656
