### ISSUE TITLE
Remove "Forum support" from menu

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#481]
<img width="460" alt="Screenshot 2022-09-20 at 12 19 59" src="https://user-images.githubusercontent.com/95082155/191767616-a88abc89-5fc2-4c59-87d5-244472e765cf.png">

**Comment by mikozet** [comment]
Hi @triaslucia 
My assumptions is that we shouldn't remove "Forum support" link from other places like login page and welcome page?
They link to https://chat.joincircles.net/home
![Zrzut ekranu 2022-09-29 o 10 58 51](https://user-images.githubusercontent.com/95082155/192990276-3524e81b-508b-4511-8125-0b755df46af6.png)

**Comment by triaslucia** [comment]
WE agreed on cancelling the Rocket chat as an option, we want to start reducing the diversification of platform in which we gather feedback / questions. So instead of a hyperlink in there I suggest to put the following 

"Questions? write us to hello@joincircles.net "
