### ISSUE TITLE
Refactor text styles

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#482]
We should refactor all text styles on our wallet. 

**Design Material** https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4673%3A9745

**Comment by louilinn** [comment]
@mikozet will upgrade MUI version at the same time

**Comment by louilinn** [comment]
Task break down
- [x] Create font styles in themes / text variants
- [x] Apply variants to all places we have text
- [x] Delete old and redundant css for text

**Comment by triaslucia** [comment]
<img width="444" alt="Screenshot 2023-06-06 at 10 31 41" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/86862b18-2d9e-4aeb-b5eb-444963c15b1a">
Hyper links in the On-boarding of SW are not correct. These should be the same style as all hyperlinks. See example bellow:
<img width="444" alt="Screenshot 2023-06-06 at 10 34 32" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/93801f3f-e46f-432c-a723-d6f33bfa2efe">

**Comment by triaslucia** [comment]
Note and explanatory text on card component, should be fixed. 
Hyperlink on cards should be fixed. 
<img width="581" alt="Screenshot 2023-06-06 at 10 22 39" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/f59b850a-365b-49e7-81b1-88f4293206fa">
<img width="583" alt="Screenshot 2023-06-06 at 10 22 24" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/e32e943b-a88a-4190-ac43-139d7b8b92d3">

It should be style: body text 4- Noto Sans Regular 14px | Text align left 

<img width="845" alt="Screenshot 2023-06-06 at 14 36 48" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/f52d8ad7-2e89-47ed-bb7a-73d264ba48c9">
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?type=design&node-id=4673-9745&t=RFYJou7coWgfh68A-0

**Comment by triaslucia** [comment]
Magic words style should be fixed. It should be Body 4 -  Noto Sans Regular 14px | Text align left
<img width="617" alt="Screenshot 2023-06-06 at 10 25 07" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/345712c0-852d-4593-9397-46e489f92600">

**Comment by mikozet** [comment]
Hi @triaslucia all is done now :)

**Comment by triaslucia** [comment]
Hoover effect from Hyperlink is missing. It is a color change. 

here for light background: 
<img width="646" alt="Screenshot 2023-06-07 at 17 28 43" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/b607d45b-468a-437f-8869-886df9b6de99">

here for dark background: 
<img width="561" alt="Screenshot 2023-06-07 at 17 35 15" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/a7240449-82e8-4a94-b207-db6e9f24955d">

**Comment by mikozet** [comment]
Hi @triaslucia, updated hover effect

**Comment by triaslucia** [comment]
Great @mikozet , this is ready for release
