### ISSUE TITLE
Re-design of Success messages notifications

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#493]
New design of the notifications. It includes new icons, colors, and behavior.

Design Material: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7556%3A14378

**Comment by mikozet** [comment]
- [x] Create notifications from new designs, update types
- [x] Update types of notification - successfully trust, revoke trust, successfully add member, UBI payments received, successfully add member, successfully remove member
- [x] Update text in notifications
- [x] Add lack of internet notification
- [x] Add Welcome notification once user enters dashboard for first time
- [x] Add notification once user receive Circles sent from different user (in progress)
