### ISSUE TITLE
 Display do not refresh msg 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#494]
SW creation process is crashing many times, because people refresh the loading page. We will include a msg saying to be pacient and do not refresh until the wallet is done. 

**Design Material** https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7556%3A15680

**Comment by louilinn** [comment]
This includes 
- [x] changing the current grey banner component design 
- [x] customize color
- [x] allowing customizable icon
- [x] update current grey banners to blue banners with the bell icon (default)
