### ISSUE TITLE
"Your circles account is loading" indefinetely, not being able to exit

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#506]
**Describe the bug**
Users get stuck with a spinning wheel saying your account is loading. 
Currently seems to affect all new users.

**To Reproduce**
1. Create a new personal wallet (with UBI)
2. Get 3 validations
3. Click create account
4. See problem beeing stuck forever

There is no way to exit this process (except for using developer tools and editing local storage)

**Expected behavior**
After a while the account should be created and usable, not more than a few minutes later. Some users are stuck for weeks or more

**Screenshots**
Will be posted below

**Devices**
Problem seems agnostic to device and browser

**Additional context**
This has existed before, especially during heavy loads
Related from launch: https://github.com/CirclesUBI/circles-myxogastria/issues/121

**Comment by mikozet** [comment]
Circles.garden screenshots:
![Zrzut ekranu 2022-10-6 o 16 06 56](https://user-images.githubusercontent.com/95082155/194339450-ecd15594-1851-4a61-b9be-6ce805d56f98.png)
![Zrzut ekranu 2022-10-6 o 16 07 18](https://user-images.githubusercontent.com/95082155/194339467-4d7084b3-da3a-4ec5-a66c-ba8790cfdc94.png)
![Zrzut ekranu 2022-10-6 o 16 07 25](https://user-images.githubusercontent.com/95082155/194339468-77bfd4a6-b104-488d-b832-9f01feea98f9.png)
![Zrzut ekranu 2022-10-6 o 16 13 35](https://user-images.githubusercontent.com/95082155/194339471-be50693d-d686-4e54-bd1e-7510159a1827.png)
![Zrzut ekranu 2022-10-6 o 16 07 03](https://user-images.githubusercontent.com/95082155/194339458-889eab4c-1868-4864-8a55-149b546ae91a.png)
![Zrzut ekranu 2022-10-6 o 16 07 11](https://user-images.githubusercontent.com/95082155/194339463-4d677c1a-57bb-41c2-b2ee-2216692a5e04.png)
![Zrzut ekranu 2022-10-6 o 16 06 41](https://user-images.githubusercontent.com/95082155/194339443-30d250f4-a26b-44dd-b48e-7b79ab524b14.png)
![Zrzut ekranu 2022-10-6 o 16 06 31](https://user-images.githubusercontent.com/95082155/194339425-90192b51-65a4-4bde-b385-9540f37d9409.png)

**Comment by mikozet** [comment]
Main branch on localhost (going correctly through the process)
![Zrzut ekranu 2022-10-6 o 16 22 21](https://user-images.githubusercontent.com/95082155/194339717-8044a0de-9526-490b-9f82-9fea49dd3a21.png) 
![Zrzut ekranu 2022-10-6 o 16 22 28](https://user-images.githubusercontent.com/95082155/194339720-53bd8f70-9b5b-4459-8b88-b06d19e2556a.png)
(
![Zrzut ekranu 2022-10-6 o 16 22 33](https://user-images.githubusercontent.com/95082155/194339721-26414f5f-3528-4102-b779-97e2f71d6aee.png)
![Zrzut ekranu 2022-10-6 o 16 22 48](https://user-images.githubusercontent.com/95082155/194339724-72136881-0192-4196-9f22-f1f2df9f9cff.png)
![Zrzut ekranu 2022-10-6 o 16 22 55](https://user-images.githubusercontent.com/95082155/194339731-954d9f16-ee50-440b-b46a-679bbf358083.png)
![Zrzut ekranu 2022-10-6 o 16 23 03](https://user-images.githubusercontent.com/95082155/194339735-5e68e1a2-7408-4731-afc0-aa1d3809bc3d.png)
![Zrzut ekranu 2022-10-6 o 16 23 19](https://user-images.githubusercontent.com/95082155/194339738-a2bffc0f-c0d2-42a7-b47b-23f4028e5347.png)
![Zrzut ekranu 2022-10-6 o 16 23 26](https://user-images.githubusercontent.com/95082155/194339742-873b335a-ae9d-4226-a589-42257db24a54.png)
![Zrzut ekranu 2022-10-6 o 16 23 45](https://user-images.githubusercontent.com/95082155/194339744-34399fd5-15c8-4189-a4e0-678b6c4da8d3.png)
![Zrzut ekranu 2022-10-6 o 16 22 17](https://user-images.githubusercontent.com/95082155/194339712-932a9e97-e157-473e-98d3-97c3ec2b4b90.png)

**Comment by louilinn** [comment]
Current theory:
safe.token.deploy never returns
https://github.com/CirclesUBI/circles-core/blob/72283bc454d142d87352b06a8969e612eb6124e1/src/token.js#L205

Bringing us to the relayer call that is made here inside executeSafeTx: https://github.com/CirclesUBI/circles-core/blob/72283bc454d142d87352b06a8969e612eb6124e1/src/utils.js#L974

So in myxo, deployToken never returns https://github.com/CirclesUBI/circles-myxogastria/blob/64611fe88d5fce54dec8403c6755eedf26af97d5/src/store/token/actions.js#L36

and so finalizeNewAccountNever reaches unlockSafeDeployment which remove loading page https://github.com/CirclesUBI/circles-myxogastria/blob/492db49cb696ae7d6dbf216e8d6e72b55e0c335b/src/store/onboarding/actions.js#L185
 
This explains why organizational accounts are not affected, as their creation does not require a token to be deployed

**Comment by llunaCreixent** [comment]
In our system the relayer is responsible of funding the account creation with the necessary xDai to deploy the Safe sign up the Hub, and deploy the Token contract. The amount that was set to be transferred is not enough because the cost increased, so we had to update that number to cover all the costs (https://github.com/CirclesUBI/safe-relay-service/pull/60).

The affected accounts, which are stuck in the validation step end up in the following state: the Safe is deployed but it hasn't signed up to the Hub (therefore no Token deployed). To move forward they need to get more xDai into the Safe address (0.0005 xDai is enough), and attempt the Account Creation again. Unfortunately, this xDai transfer has to be done manually.

Accounts that haven't tried the validation process yet will succeed.

Both this issue and https://github.com/CirclesUBI/circles-myxogastria/issues/121, are fixed with https://github.com/CirclesUBI/safe-relay-service/pull/60.
