### ISSUE TITLE
Max amount between shared wallets displaying wrong max flow value

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/circles-myxogastria#540]
**Describe the bug**

A shared wallet wanting to send CRC to another SW, the max flow amount is displayed incorrectly

**To Reproduce**
1. Go to a shared wallet profile
2. Click on  send circles
3. wait until max amount is displayed 

**Expected behavior**
The max flow amount in time circles

**Screenshots**

<img width="807" alt="Screenshot 2022-11-21 at 18 56 21" src="https://user-images.githubusercontent.com/55389166/203127631-86cef303-2bd4-4c9d-9b25-0e30d84f1979.png">

**Additional context**
Use this query to check the value returned from the API, this comes in Circles ( so a conversion is needed to time circles)

`{"from":"0x3c89A829400Ea3B49F25738A1F4015A7961D0301","to":"0x9BA1Bcd88E99d6E1E03252A70A63FEa83Bf1208c","value":"1000000000000000000000000000000000"}`

response 
```
{
	"status": "ok",
	"data": {
		"from": "0x3c89A829400Ea3B49F25738A1F4015A7961D0301",
		"to": "0x9BA1Bcd88E99d6E1E03252A70A63FEa83Bf1208c",
		"maxFlowValue": "29100587751936619099862",
		"processDuration": 154335,
		"transferValue": "1000000000000000000000000000000000",
		"transferSteps": []
	}
}
```

**Comment by JacqueGM** [comment]
This might go a way with the new pathfinder implementation 
Related https://github.com/CirclesUBI/circles-transfer/pull/14

**Comment by JacqueGM** [comment]
@louilinn  maybe we can close this issue with your supeer  hops implementation?

**Comment by louilinn** [comment]
Yes true! :dancers: when we release :)
