### ISSUE TITLE
Make notification logic work for news tab

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#543]
Part of https://github.com/CirclesUBI/circles-myxogastria/issues/396

Functionality of the badges that shows number of notifications
- [x] the number of new news notifications should be aggregated in on the badge on the bell icon on dashboard
- [x] the number of news notifications should be nulled when news tab is opened. The badge disappears and does not aggregate in dashboard anymore
- [x] unread news notifications should automatically be open when entering the news tab

@triaslucia you are welcome to confirm this behaviour
This is not yet implemented

**Comment by mikozet** [comment]
To integrate with [Trust activity is not opened when entering activity log](https://github.com/circlesubi/circles-myxogastria/issues/570)] would be good and much easier to have API already made
