### ISSUE TITLE
Stuck forever in search mode while trying to search for a user

### ISSUE THREAD

**Issue by samuelandert** [CirclesUBI/circles-myxogastria#55]
<img width="941" alt="Bildschirmfoto 2020-06-05 um 21 39 23" src="https://user-images.githubusercontent.com/747161/83916257-24490980-a775-11ea-9922-a7f7da3a2ab4.png">

**Comment by adzialocha** [comment]
This issue is filed here as the fix has to be done on API level: https://github.com/CirclesUBI/circles-username-resolver/issues/9
