### ISSUE TITLE
Downloadable Monthly Balance 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#556]
**So far people have to manually write down all income and outcome of heir wallet in external documents to do taxation**
people depend on manually create excel sheets to do their monthly taxation work

**Download the wallet balance**
People should be able of download the monthly balance in CVS format and work all data at once

**FIRST STAGE **
We will start by providing the possibility of setting time-span and export on CVS format.

**Design Material**
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7523%3A11295&t=5K5oFQLFcGzsxVzG-1

**Comment by louilinn** [comment]
Replaced by epic: https://app.zenhub.com/workspaces/circles-garden-63764cdd7a20fed2a58bf8cf/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTE2MDM2
