### ISSUE TITLE
Transactions spliting Received-sent 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#558]
**People should be able to see a split view of their transactions.**
while standing on the Activity Log screen on the "transactions" tab, people should be able to choose to display only the received or only the sent transaction - apart from the already existing overall view order by date. This is helpful for business to be able to track better the payments the receive. 

**Design Material**
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?type=design&node-id=9427-16806

**Comment by louilinn** [comment]
Starting this sprint we work on this. But it will take longer. Lower prio than news

**Comment by triaslucia** [comment]
Looks in general good. I just want to double check:
1.Size of the text  on the drop down menu needs correction. Dropdown text is supposed to be Body 7 also. Looks big to me. 
2. We will remove the underline, for the selected option. Keep only the bold. 

See figma:https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Product-and-UX-design-circles.garden-(Circles-myxogastria)?type=design&node-id=9427-17040&mode=design&t=l5FGrkIvytEeYv9j-0
