### ISSUE TITLE
Badge and notification logic + Trust activity is not opened when entering activity log

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#570]
**Describe the bug**
When a trust event has happened, such as
- trusting or untrusting another account
- being trusted or untrusted by another account
it triggers a badge in the activity log bell.
Upon entering the activity log, the user is referred to the transaction log where nothing has changed. 
The connections log is not opened automatically and shows no badge

**To Reproduce**
1. Enter the activity log first if there are unopened notifications
2. Go to another account and trust or untrust it
3. Go back to the dashboard and wait for the loading wheel to stop spinning on the bell icon
4. See a badge with a 1 (1 new notification)
5. Enter the activity log by clicking the bell
6. Experience the "bug" above
7. Enter the connections tab and see a dot indicating a new notification that wasn't evident before explicitly switching tab.

**Expected behavior**
When entering the activity log I would expect the tab with the highest number to open automatically. If they are even (2 of each for example), start from the left. In the case above this would cause the connections tab to open. If there are notification in multiple tabs I expect the other (non-opened) tab(s) to have badges with numbers of unread notifications. Similar to how badges show in search tabs.

**Device**
All devices.

**Additional context**
Use search view badges as inspiration. Make sure figma design is up to date.

**Comment by louilinn** [comment]
@triaslucia 
Could you link the appropriate design material to this issue if you agree and check that it includes this functionality?
This is related to how we implement news log

**Comment by louilinn** [comment]
Related: https://github.com/CirclesUBI/circles-myxogastria/issues/543

**Comment by mikozet** [comment]
- [x] when entering the activity log the tab with the highest number open automatically
- [x] if they are even (2 of each for example), start from the left
- [x] Ii there are notifications in multiple tabs we expect the other (non-opened) tab(s) to have badges with numbers of unread notifications
- [x] ignore above when user decide to choose category by himself using proper link (eg. http://localhost:8080/activities?category=connections)
- [x] fix when user use http://localhost:8080/activities link (we check for highest activities value and activate category based on that)

**Comment by triaslucia** [comment]
Behaivour: 

-Open the Activity log screen
-by default I am on the Transaction menu. and this icon should show in active state the number of unread notifications. 
-All unread notification of transactions will be marked with a red dot in the top-right corner.
-The red dot and the notification budge should be connected - every-time one notification is red, should be discounted from the number appearing on the transaction icon budge.

-Notifications should consider red if: people click on the card and display the information and if they remain in the screen for 2s.
- For each card appearing when scrolling down, 2s should be consider for each-one to be marked as read as well. 
- If people scroll down multiple times fast , notifications should remain unread.

**Comment by louilinn** [comment]
Closed by https://github.com/CirclesUBI/circles-myxogastria/pull/600/commits/cf2f18767730e5e9651bce42dbc197ea75b85e8f
