### ISSUE TITLE
use http instead of ws for the Ethereum node

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#574]
Related: https://www.reddit.com/r/ethdev/comments/gp97aq/infura_https_vs_wss_is_there_ever_a_reason_to_use/

this is a possible solution for the following issue:
- https://github.com/CirclesUBI/circles-myxogastria/issues/134

Reference to email "Fwd: Request #15073: How would you rate the support you received?" to quicknode

**Comment by louilinn** [comment]
[https://circles-ubi.sentry.io/issues/3603872449/?project=5446133&query=is:unresolved&referrer=issue-stream&sort=user&statsPeriod=90d](https://circles-ubi.sentry.io/issues/3603872449/?project=5446133&query=is%3Aunresolved&referrer=issue-stream&sort=user&statsPeriod=90d)

**Comment by louilinn** [comment]
If this doesn't work, we should use refresh notification when connection is lost

**Comment by JacqueGM** [comment]
@llunaCreixent  will review this and then it can be closed :)

**Comment by mikozet** [comment]
movet to https://github.com/CirclesUBI/circles-myxogastria/pull/719
