### ISSUE TITLE
Re-design banner design 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#577]
As part of our refactoring work we are implementing a new design of all our Notification System. 

Here the design of our banner msg: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=8479%3A22781&t=3zxJOo61iiTxU3nj-1

**Comment by mikozet** [comment]
Related to https://app.zenhub.com/workspaces/circles-garden-63764cdd7a20fed2a58bf8cf/issues/gh/circlesubi/circles-myxogastria/494
Can be closed once PR from above is merged. I am not able to connect PR to this task somehow..
