### ISSUE TITLE
Display generic msg in case of wallet downtime

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#578]
**display a downtime alarm msg- to minimize the panicking among users **
Scenario #1: In case Lucia is available,  we should write  a descriptive msg, explaining the actual cause of the downtime. 
Scenario #2:  in case Lucia is not  available, we should display the generic text 

**#1 in case of downtime we should display ASAP this generic msg**
Sorry our system is facing some issues and we are working to fix them ASAP. Once fixed, everything will be back to normal, like your UBI and wallet balance. Thank you for your patience!

**#2 update msg*
Once we have particular information about the actual issue, we should update the msg explaining the specific problematic and if possible fixing times.

**Comment by louilinn** [comment]
These instructions have now been added to our internal work processes in case of downtime.
