### ISSUE TITLE
Retry on fail for transactions and max flow calculation with fewer max_hops sent to api and pathfinder

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#580]
We recently upgraded the API (1.8.1) in production to include pathfinder 2.0.
This version allows for a maximum number of trust hops away from them sending user inside the trust network for finding transaction steps. The default number of hops for this version is 3.

The transfer request (to get the transaction steps) often times out for users with complex trust networks. Therefore we want to lower the number of hops and retry finding a path if it times out. Fewer hops requires less computation.
We want to retry with hops = 2 on fail for both max transfer and send.

There are thoughts about saving max hops in local storage as well but not expected in resolving this issue.

**Comment by louilinn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/circles-myxogastria/580?planning-poker) with Zenhub @louilinn @mikozet

**Comment by llunaCreixent** [comment]
What do you think about checking also the steps number to not be more than ~50 (or maybe less, we might have to study the gas limits again) in the new retry method? @louilinn

**Comment by louilinn** [comment]
@llunaCreixent So when we get the error from [here](https://github.com/CirclesUBI/circles-core/blob/cd8c6002c6a4adcf4ace50d303d1b32877e03ee3/src/token.js#L433) we also lower the hops?
I think this will happen automatically as it leads to transfer fail, just like time out?

**Comment by llunaCreixent** [comment]
> @llunaCreixent So when we get the error from [here](https://github.com/CirclesUBI/circles-core/blob/cd8c6002c6a4adcf4ace50d303d1b32877e03ee3/src/token.js#L433) we also lower the hops? I think this will happen automatically as it leads to transfer fail, just like time out?

Sounds good
