### ISSUE TITLE
wrong message when updting version

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#585]
When I log in with an account with an old version of the safe, the message says... "Infoupdatedversion"

**Comment by mikozet** [comment]
The error comes from missing translation..
It looks like it was implemented but dissapeared maybe due to rebase (?) 
@louilinn could you write what was the update message. As I remember it was sth like "Safe version has been updated to <version> version" ?

**Comment by louilinn** [comment]
I think we should not inform the user with a pop up for this. That was our previous decision. So the pop up should be removed
