### ISSUE TITLE
Some transfer-steps are invalid in a transaction

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/circles-myxogastria#587]
Some of the transfer steps returned for a transacion are invalid, meaning, they are not possible to carry out because of the balances between sending/receiving accounts.

**Comment by louilinn** [comment]
We should look over error handling in send confirm.

We fail to catch a 422 from the relayer. It arrives after the sucess message is displayed - should wait?

**Comment by louilinn** [comment]
Is this different from https://github.com/CirclesUBI/circles-myxogastria/issues/589 or dublicate? @JacqueGM jacque
Sounds like this is more on the api side?

**Comment by louilinn** [comment]
Not needed with new pathfinder service using different indexer
