### ISSUE TITLE
Max flow returned with more than 52 steps

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/circles-myxogastria#588]
With the new implementation of the pathfinder we get  the transfer steps for a transaction, but currently there is a limitation of 52 steps which doenst allow to send all the max flow. We need to limit the max-flow calculation to a realistic amount within the 52 step limitation.

**Comment by louilinn** [comment]
The Maxflow is found by this request:
https://api.circles.garden/api/transfers/ with request
`{"from":"xxx","to":"yyy","value":"1000000000000000000000000000000000","hops":"3"}`

The response from the api request for max flow is as follows:
`{"status":"ok","data":{"from":"xxx","to":"yyy","maxFlowValue":"3136526450909334179879","processDuration":58434,"transferValue":"1000000000000000000000000000000000","transferSteps":[]}}` 
which does not include transfer steps. Thus the app cannot verify the number of steps for the maximum amount is less than 52

**Comment by louilinn** [comment]
Solved by new pathfinder service
