### ISSUE TITLE
Transaction of high amount are being reverted

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/circles-myxogastria#589]
**Describe the bug**
When sending high amounts (>8k) the transactions are reverted but the message says transaction done.

**To Reproduce**
1. Go to transfer CRC
2. Click on  send
3. Wait until transaction takes place

**Expected behavior**
Transactions should be done and if they are not done a proper message should be returned, but not a success message
**Screenshots**
[](url)

**Desktop-Computer (please complete the following information):**
 - Chorme

[
<img width="1375" alt="Screenshot 2023-01-30 at 14 15 47" src="https://user-images.githubusercontent.com/55389166/215552997-b6137479-0772-4b50-9f93-315c5eb6c6d4.png">

<img width="1428" alt="Screenshot 2023-01-30 at 14 57 52" src="https://user-images.githubusercontent.com/55389166/215551834-ae78dd64-5d6d-48d2-877b-ebe3af6a83af.png">
](url)

**Comment by JacqueGM** [comment]
https://github.com/CirclesUBI/safe-relay-service/blob/v5.0.2-pre-g8ac7fc4/safe_relay_service/relay/services/transaction_service.py#L628

**Comment by JacqueGM** [comment]
https://github.com/safe-global/safe-eth-py/blob/v4.8.1/gnosis/safe/safe_tx.py#L313

**Comment by mikozet** [comment]
I havent been able to replicate this issue. For me the app throws an error but stays endless at a loading screen. I applied a code which close loading spinner and popup notification that something is wrong..
![Screenshot from 2023-03-09 13-56-442](https://user-images.githubusercontent.com/95082155/224087129-cc67575e-796d-4bf9-966f-437513968c4e.png)

**Comment by louilinn** [comment]
Could be that there are too many steps for one block. We should handle the error. We should also lower the max transfer steps (research new number).

**Comment by louilinn** [comment]
This task is about handling the error and communicating it to the user

**Comment by mikozet** [comment]
This PR https://github.com/CirclesUBI/circles-myxogastria/pull/627

doesn't solve issue in the task. It is related to forever loading screen which can be found in this task:
https://github.com/CirclesUBI/circles-myxogastria/issues/611

**Comment by JacqueGM** [comment]
With the update of the database of the relayer, we have not seen revert message but other issues such as the feetoolow, we will keep a check on this for this week and to confirm this assumption @juanenrisley

**Comment by JacqueGM** [comment]
it's actually keeps happening but we can reproduce, if you loggin as EraBox and try to send 1000 from EraBox to Coop  you will see the Transaction being reverted.
