### ISSUE TITLE
Transferring circles message

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#590]
-Transfer can take long sometimes, therefore we will implement a modal with a msg asking for patient and displaying a loading animation. 

-here design material: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=8692%3A22818&t=NN5XyKajk1K4swZU-1

**Comment by louilinn** [comment]
branch working branch from branch "main"

**Comment by mikozet** [comment]
- [x] add new dialog and logic
- [x] refactor by creating additional componet SendConfirmDialog

**Comment by triaslucia** [comment]
I do not see the modal on the transferring process. Just the spinning wheel as before. 

<img width="469" alt="Screenshot 2023-03-01 at 11 30 36" src="https://user-images.githubusercontent.com/38475134/222114396-03fb390e-a54b-4224-8cb3-dbbfc1820883.png">
