### ISSUE TITLE
Feedback on first refactoring release

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#609]

**Comment by triaslucia** [comment]
**Activity log screen icons**
when then number of notification is of 2 digits it is not centered. 
![Screenshot 2023-02-16 at 09 48 26](https://user-images.githubusercontent.com/38475134/219315337-fab1fadf-cc96-42c3-8383-d90ee69a9f07.png)

*Circular "..." button does not look good*
The size scale between circle and the dots is not good. 
![Screenshot 2023-02-16 at 09 53 14](https://user-images.githubusercontent.com/38475134/219316008-8533fd36-03fc-4d62-bf8d-110673407d48.png)

-Is it possible to update it to the new design (new circular shape)?
-the hand written shape of the circles is not ready. So we will push it later. 

**Buttons text style**
-We need to correct the text style. Each word should start with Capital. 
![Screenshot 2023-02-16 at 10 28 01](https://user-images.githubusercontent.com/38475134/219324326-f24a8f49-cb03-4bf8-aecc-2655ab4e029a.png)

**Notifications**
Some behaviors is not de desire, mostly the fact that many notifications will be displayed all together one on top of it. 

- Compromise for now: we should apply a default 10s disappearing setting.
- Lucia will do a broader work on the different scenarios to continue with behavior work.

**Comment by triaslucia** [comment]
**Scroll down shadow** 
It is too rectangular. We should increase the blurring so that it gets gradually lost, for this it is necessary to increase the height of the surface that covers the shade. 
![Screenshot 2023-02-16 at 09 57 36](https://user-images.githubusercontent.com/38475134/219317153-d300c050-7d9c-464f-a99d-733d7dd88ffb.png)

**Comment by louilinn** [comment]
**Notification duration**
Update: All notifications have lifetime 10 000 ms = 10 s.
Only exception is internet connection that persists until you have a connection again
