### ISSUE TITLE
Steps returned are not valid

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/circles-myxogastria#610]
The steps returned from the pathfinder are not valid because the balances from the accounts are not up to date, therefore transactions cannot be processed. 

This is likely to be solved by  the new pathfinder service

**Comment by louilinn** [comment]
Why is this issue in myxogastria? I think it should be in core or api, as it relates to replacing the pathfinder api?
And maybe linked as related in this issue: https://github.com/CirclesUBI/circles-myxogastria/issues/589

**Comment by louilinn** [comment]
I am closing this issue @JacqueGM please create an issue in other repos if needed. This issues does not describe a user interface experience and should not be in myxogastria. 

If you like to reopen it please describe a user scenario using bug template as a guide
