### ISSUE TITLE
Loading screen forever after updateTransferSteps

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/circles-myxogastria#611]
**Describe the bug**
After the updateTransferSteps - the transactions are not being retried therefore the screen remains in a loading page
**To Reproduce**
1. Go to circles.garde
2. Click on send and open network tab
3. Wait until it finished the whole sending process.
4. Observe that after the update steps the transaction are not retried ending up in a forever loading screen

**Expected behavior**
After update steps the transaction should be retried and a message should be shown on what is happening

**Screenshots**
<img width="1414" alt="Screenshot 2023-02-15 at 16 12 56" src="https://user-images.githubusercontent.com/55389166/219068069-29e784ef-e215-4b91-91c5-c0dae69810ed.png">

**Desktop-Computer (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by louilinn** [comment]
waiting for replacement of pathfinder service first

**Comment by mikozet** [comment]
This PR might be helpfull for this task: https://github.com/CirclesUBI/circles-myxogastria/pull/627
As it solves issue in coment described here:
https://github.com/CirclesUBI/circles-myxogastria/issues/589#issuecomment-1462356650

**Comment by juanenrisley** [comment]
As seen with @JacqueGM this issue is caused by #644. We tested in https://preview-dev.circles.garden/ and does not occur anymore.
