### ISSUE TITLE
Export Balances - add option for "last month"

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#624]

**Comment by louilinn** [comment]
- https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7523-11295&t=VtAkrRww9liYOQpk-0#394798365 SECOND STAGE WITHOUT PDF
 
Includes
- Adding the selection boxes between last month and customized dates
- Export adjustment for when last month option is chosen
- Default behaviour to last month

**Comment by louilinn** [comment]
Partly done as date inteval defaults to last month. Do we still want to add this button in the future @triaslucia ?

**Comment by triaslucia** [comment]
Yes, this will come in a next iteration -ideally- together with the PDF option.

**Comment by louilinn** [comment]
Cleaning up as work scope has changed. Pre-selected dates are already providing last month option by default
