### ISSUE TITLE
Hyperlinks in popup and left side menu should have more prominent color (probably white)

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#626]
![Screenshot from 2023-03-08 13-06-19](https://user-images.githubusercontent.com/95082155/223672930-d263283f-7631-4925-801f-35f140820450.png)

**Comment by louilinn** [comment]
@triaslucia can you assign prio? :)
Related: #579

**Comment by triaslucia** [comment]
I cannot reproduce the example on the picture above. For me it looks good, like in our designs. 
<img width="749" alt="Screenshot 2023-04-05 at 15 37 03" src="https://user-images.githubusercontent.com/38475134/230097730-4521318d-4ade-40d5-86c9-1d054b1e0049.png">

Anyways, whatever inconsistency will get solved with the text refactoring.  I am closing this issue.

**Comment by louilinn** [comment]
This issue is closed as it was resolved in the latest release :)
