### ISSUE TITLE
Notifications of receiving Circles to personal wallet, are displayed on the shared wallet

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#629]
**Describe the bug**
Notifications of receiving Circles to personal wallet, are displayed on the shared wallet

**To Reproduce**
1. Go to a shared wallet that you own and which holds circles you can transfer to your personal wallet.
2. Send Circles to your personal wallet
3. See the success message for the transaction
4. Wait (in your shared wallet)
5. See a received message notification for the transferred Circles arriving to your personal wallet

**Expected behavior**
Step 5 should not happen unless you are back in your personal wallet.

https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=9211-21071&t=hr3EsnnFUt5qYu24-0

Related: #529

**Comment by louilinn** [comment]
@triaslucia this is filed, update priority if as you wish

**Comment by llunaCreixent** [comment]
I also saw the issue when I'm logged in my personal wallet and I see the notifications of my SW

**Comment by triaslucia** [comment]
what notification do you see on the SW @llunaCreixent , like if someone transfers CRC to a SW you got the notification on your Individual one? 

@louilinn Is it possible to add to each notification the name of the wallet directly affected to the action the pop-up is related to? if yes I can work on making the design change on the notification to always include this.

**Comment by triaslucia** [comment]
<img width="902" alt="Screenshot 2023-04-05 at 16 58 40" src="https://user-images.githubusercontent.com/38475134/230121337-e97533fa-2fd8-4583-9405-49ce08f935c2.png">

1. I open my individual wallet, and a SW at the same time
2. Transfer 10 CRC from the individual to the SW 
3. Got the notification of "successfully send 10 CRC" on the individual wallet. 
4. I get on both wallets at the same time the notification of "having received the CRC"

**Comment by llunaCreixent** [comment]
> what notification do you see on the SW @llunaCreixent , like if someone transfers CRC to a SW you got the notification on your Individual one? 
> 

@triaslucia I did the same test as you

**Comment by louilinn** [comment]
It also sometimes happens that you gt a received notification even if you don't have access to the receiving wallet.

**Comment by louilinn** [comment]
@triaslucia What I remember we have said in our meetings was to not have notifications pop up for other wallets, except ubi. So I don't think we need new designs? We would just fix this bug as in removing received notifications for wallets that you are not in atm.

**Comment by louilinn** [comment]
To do:
- [ ] this has also been reported to happen to wallets that you do not own - look into how this can happen
- [x] remove received notifications for other wallets than your own

**Comment by mikozet** [comment]
regarding: 
- [ ]  this has also been reported to happen to wallets that you do not own - look into how this can happen

I believe it should be corrected as well although I wasn't able to replicate it and tested it
