### ISSUE TITLE
Use pathfinder2 service

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#631]
By default the pathfinder type is `server`. However, we can get same behavior as before by keeping the value to `cli`.
Note that in case of using the type server, the parameter `hops` will be ignored, otherwise (with type cli) the `maxTransfers` parameter will be ignored. Therefore, we should review the logic using the hops to optimize the transfer steps response (https://github.com/CirclesUBI/circles-myxogastria/pull/597).

**Comment by llunaCreixent** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/circles-myxogastria/631?planning-poker) with Zenhub @juanenrisley @louilinn

**Comment by louilinn** [comment]
In preview-testing only

**Comment by louilinn** [comment]
Blocked by waiting for CORS settings from other team
