### ISSUE TITLE
Export Balance UI for first stage - visual part and popup functionality with date selection

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#633]
Design material:
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7523-11295&t=VtAkrRww9liYOQpk-0#394798365 - FIRST STAGE

Create the graphical interface and allow for date selection.
The download behavior is set to the export button in design.

This task does not involve manipulating downloadCsvStatement or file statement. It is only the UX parts.
(see task issue #623 for next functionality task)

**Comment by louilinn** [comment]
Can you push whatever code you have so far to a PR @mikozet ?

**Comment by triaslucia** [comment]
1_Input field for Time Span should be customized.
Base color, hoover, shape. 
![Screenshot 2023-04-20 at 11 47 15](https://user-images.githubusercontent.com/38475134/233328970-4150e543-913e-42a2-b4c0-80bb1031339e.png)

2_ Explanation text color should be fixed. Should be purple 
![Screenshot 2023-04-20 at 11 47 09](https://user-images.githubusercontent.com/38475134/233328939-82dcf61e-2b5b-49b6-a624-1ca56653d3a5.png)

3_The modal screen is always on Mobile size.  Should be fix to desktop size and made reactive. 

 
![Screenshot 2023-04-20 at 11 04 30](https://user-images.githubusercontent.com/38475134/233329250-e8252331-3c7a-4491-980c-d7cf1f1f6396.png)

4_Hoover is missing on  Export statement 
![Screenshot 2023-04-20 at 11 53 23](https://user-images.githubusercontent.com/38475134/233330795-3dd8846a-3c63-47b7-b363-04f0121b655c.png)

**Comment by triaslucia** [comment]
@louilinn @mikozet  I noticed that regarding time span. 

1- It is not possible to search for a time span older than 1 year ago 
2- It is not possible to ask for an export of a time span longer than 3 months. 

Both things are ok for me. Just wanted to ask if this were decision you took, or if it is sort of like the "default".

**Comment by mikozet** [comment]
Hi @triaslucia  thx for feedback a question regarding desktop version. I am not sure how it should look like there... 
What should be size of dialog (width)?
Do we change that curved line for longer version or dialog should be wider but content kept inside container size of current curved line.. ?

**Comment by triaslucia** [comment]
I think we should keep the same logic as on other modal screens.

-The screen size is the same size as the main screen.
-Content remains centered, and margins are wider than on mobile version. 
eg. 
![Screenshot 2023-04-20 at 12 28 55](https://user-images.githubusercontent.com/38475134/233339864-c0efc0c2-58e1-4a53-8509-691bd94ee563.png)

**Comment by triaslucia** [comment]
another fix: 

5- The notification of success is still missing! 
![Screenshot 2023-04-20 at 12 33 48](https://user-images.githubusercontent.com/38475134/233341009-d6a4f75a-40e1-4139-8901-b50908539a7f.png)
![Screenshot 2023-04-20 at 12 33 54](https://user-images.githubusercontent.com/38475134/233341019-24e4098d-8d57-4d48-878a-da955ff5ec94.png)

**Comment by louilinn** [comment]
@triaslucia 
### Notifications
The notifications will be fixed in another task. I will file a new sub-task, haven't done that since they were added yet :)
https://github.com/CirclesUBI/circles-myxogastria/issues/664

### Dates
We can continue dates discussion here:
https://github.com/CirclesUBI/circles-myxogastria/issues/623

**Comment by louilinn** [comment]
> I think we should keep the same logic as on other modal screens.
> 
> -The screen size is the same size as the main screen. -Content remains centered, and margins are wider than on mobile version. 

![Screenshot from 2023-04-18 11-38-06](https://user-images.githubusercontent.com/20553836/233348976-29b0f3f5-8e38-44ac-b646-632133ecbd91.png)

This is the other modal we have (in validation view). I think we should unionize them all :)

**Comment by triaslucia** [comment]
I recommend to take this as separate issue as a consistency task. I can make another issue for it. 
For the current task I appreciate to follow the line I mentioned above.
