### ISSUE TITLE
Undeployed account gets zero address as token address and the error should be treated differently 

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#645]
[MYXOGASTRIA-PRODUCTION-4H8](https://circles-ubi.sentry.io/issues/2253587336/?project=5446133&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=4)

When an account is not yet verified (deployed) token returned is the zero address

This should be reflected in the [core method documentation](https://github.com/CirclesUBI/circles-core/blob/0c8479cea08029f5540ba1c3aa42adbb214f0291/src/token.js#L342)

[Myxogastria code](https://github.com/CirclesUBI/circles-myxogastria/blob/551cddf24ab687469c2ac625f2fd221a47beef00/src/store/token/actions.js#L107)

We should catch the error thrown for Zero address and display an error/warning notification that this user's token has not yet been deployed or failed to deploy. - Ask product for message and tell them about the error and when it occurs.

Catch in [actions here](https://github.com/CirclesUBI/circles-myxogastria/blob/551cddf24ab687469c2ac625f2fd221a47beef00/src/store/app/actions.js#L90) and dispatch notification.

**Comment by mikozet** [comment]
Hi @triaslucia 
Current state of this task at screenshot below.
Would you like to edit error message or is it sufficient? 
![Screenshot from 2023-06-15 11-29-02](https://github.com/CirclesUBI/circles-myxogastria/assets/95082155/6682ff0f-2048-4af2-8ac6-fd6c64c347e0)

**Comment by louilinn** [comment]
blocked waiting for Lucia

**Comment by louilinn** [comment]
@triaslucia can you look at this before thursday?

**Comment by triaslucia** [comment]
Basically the msg is now quite technical and is missing information on how to proceed, which is the main function of a toast error msg. So our opinion is to go for a structure of: 
**Friendly line on the fact that an error happen** + Error explain in understandable way + what to do next

This is the msg we proposed: **Something went wrong!** We could not create your wallet. Please reset account."

_NOTE_ see that we are not aware of what expected behaivour of the user after the deployment failure it is, so we put the "Please reset account" as example, you can replace it with whatever it is the expected behaivour
