### ISSUE TITLE
Improve contrast on success notification and info banners. 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#655]
Current Success notification has not enough contrast. 
**Current state** 
Background: Blue/200
Text: Neutral (white)

**Change needed** 
We should change the background color to Blue/100 in all cases of success notification and banner. 
_See as example:_ https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=7556-15680&t=v2bDkL95BdTfYhzx-0

**Comment by louilinn** [comment]
Any priority indication on this with label?
