### ISSUE TITLE
Commas in payment notes break 'Amount_in_circles' column in exported CSV

### ISSUE THREAD

**Issue by juanenrisley** [CirclesUBI/circles-myxogastria#678]
Having commas in a payment note text adds more columns to the CSV as the syntax is comma separated for column division. This breaks the _Amount_in_circles_ column as it holds text values and not the amount, that is left behind in a new column.

For example, this payment note was: `donation, don't send back please`

![Screenshot from 2023-05-04 08-50-08.png](https://images.zenhubusercontent.com/63e50e3f472d0b732cddc904/0660c270-7305-445b-a6d6-560eb19dcd45)

**Comment by llunaCreixent** [comment]
@mikozet @louilinn do you wanna close this issue?

**Comment by mikozet** [comment]
yes I believe it is done, I am closing

**Comment by louilinn** [comment]
Resolved by https://github.com/CirclesUBI/circles-myxogastria/pull/681
