### ISSUE TITLE
Post release changes, addons after export statement release

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#680]
Add any bugs and minor fixes post release to this issue

- [ ] On the error state of the input component, when you give a wrong date, he error text says " Invalid rate" and should say "Invalid date".

**Comment by triaslucia** [comment]
we need to fix a minor aspect of the CSV format: 

change from current : 2,000.00 CRC to 2.000,00 CRC

**Comment by llunaCreixent** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/circles-myxogastria/680?planning-poker) with Zenhub @louilinn @mikozet
