### ISSUE TITLE
Unionize news component with activity log components

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#697]
Activity log entries should be like the new news items

https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?type=design&node-id=4350-26250&mode=design&t=3qY3hYPTMn0vhq6U-0

**Comment by louilinn** [comment]
Also make sure the selecting tab styling is according to the figma

**Comment by louilinn** [comment]
Approach: Refactor the item components. Extract the activtyStreamItem into a separate file and make a major component with all the styling that is used in components for user activities and news actiities. 
Suggested names: 
ActivityUserItem and ActivityNewsItem which both build on ActivityStreamItem. 
ActivityStreamItem has children (avatars/icon and the news content/ transaction details). Shared props: date title and expandable content. Something along these lines at least. We can pair program, it might save us time as this is a little tricky.
In general the ActivityStream files are very large and can use break up..

Take this mix of items into considerations: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Product-and-UX-design-circles.garden-(Circles-myxogastria)?node-id=7523%3A11365&mode=dev (trust and transfers are not always in seperate logs)

**Comment by JacqueGM** [comment]
there are questions around how to insert locally to the DB to make the sure the core is reading from the DB directly.

**Comment by mikozet** [comment]
How to insert news locally to database:
in circles-docker repo:
```
make psql
\c api      - connect to database
\dt+        - display tables
select * from news limit 1;
insert into news (message_en, date, "iconId", "isActive") values ('sadsa', '2015-03-12', 12131232, true);
\q            -  disconnect from database```

We discovered an issue with created_at, and updated_at not being created automatically, issue logged here: 
https://github.com/CirclesUBI/circles-api/issues/197
