### ISSUE TITLE
Refactoring SW illustrations

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#698]
@triaslucia to fill in the details

**Comment by triaslucia** [comment]
@mikozet Here it is the material to change the SW on-boarding illustrations: 

**Design Material** https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Product-and-UX-design-circles.garden-(Circles-myxogastria)?type=design&node-id=9824-14612&mode=design&t=3suu7oP1QmLr1mED-0

**Comment by triaslucia** [comment]
**Review**

-In general the icons are too big, and this creates problems with the explanatory text. 

<img width="444" alt="Screenshot 2023-07-11 at 13 30 27" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/f39b200e-a7c2-437f-82c5-d4d37daaf9f9">
<img width="442" alt="Screenshot 2023-07-11 at 12 40 38" src="https://github.com/CirclesUBI/circles-myxogastria/assets/38475134/592608b0-f85b-45af-a9d0-0d0da4331754">
 I added on figma, corrections to solve this. 
 
 - The top corner icons ( cross and next-previous) are in the wrong color. Should all be 100 Purple
 
See Figma.

**Comment by triaslucia** [comment]
This is ready now.
