### ISSUE TITLE
Try new pathfinder URL

### ISSUE THREAD

**Issue by juanenrisley** [CirclesUBI/circles-myxogastria#702]
The Gnoci team is offering a new URL for accessing the pathfinder: https://pathfinder.circlesubi.id/
They want us to try it out.

**Comment by louilinn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/circles-myxogastria/702?planning-poker) with Zenhub @louilinn @mikozet @llunaCreixent @juanenrisley

**Comment by llunaCreixent** [comment]
It works perfectly, test with https://preview-dev.circles.garden.
We can use `pathfinder.circlesubi.id` instead of `rpc.circlesubi.id/pathfinder `.
@jaensen  said:
> They all have the same version. The difference is that `pathfinder.circlesubi.id` relies on DNS round robin load balancing. If one of the host goes down, it's not isolated and 50% of the requests will still go to the host that's down. The new endpoint also isolates failed instances so that at max. a few requests would fail.

**Comment by llunaCreixent** [comment]
- [x] change in prod
