### ISSUE TITLE
Change illustration on Welcome and log in page 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#703]
**Update the  default profile picture on log in page**
 
_Log In page_ 

remove the old Circles illustration, with people on top. And change for the Circles Coop one, with Yellow background. 

https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Product-and-UX-design-circles.garden-(Circles-myxogastria)?type=design&node-id=9774-13062&mode=design&t=pwLWMxbM5bKJe7Dd-0

**Comment by louilinn** [comment]
@triaslucia I'm a bit confused, are we officially changing the logo of circles.garden? 
Then shouldn't we also change the tab icon, the max transfer icons, avatar for UBI payout logs, validation loading screen etc?

**Comment by louilinn** [comment]
Also maybe we can specify the release criteria of issues, such as, can it be released on its own or must it be merged with another issue at the same time. (Of c we will also confirm before merging)

**Comment by louilinn** [comment]
Known places of the current logo:

- Max transfer amount icon
- CirclesUBI payout "avatar" in activity log
- Saving the webapp to home screen on phone creates an icon image
- Validation loading screen
- Favicon / tab icon
- Preview image in links
- Login
- Welcome (with "gang")
