### ISSUE TITLE
Progress bar + info slides on loading wallet process

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#715]
**Wallet creation process crashes**
Wallet Creation process crashes many time . Due to long loading times, people tent to refresh the tab and this makes the process crash. 

**We need to better the loading experience**
- Add a progress bar that shows the 2 steps of this process, is animated and shows actual progress, and also show the accomplishment of each step
- Complement the screen with info slides, for people to have  an possible interaction with the screen while waiting. 

**Design material**
[Add any other context or screenshots about the feature request here.
](https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Product-and-UX-design-circles.garden-(Circles-myxogastria)?type=design&node-id=9207%3A20380&mode=design&t=mF7Gz6RoaL9zapmm-1)

**Comment by louilinn** [comment]
Due to technical challenges and low user value this is no longer planned
