### ISSUE TITLE
News feature: customized welcome news item

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#724]
The first news item in the news log (oldest) should be the welcome, your account has been created message. 

The displayed timestamp of this news item should be individualized to the signed up wallet. Thus it is not a regular news item.
As this is a standard message, this news item text should be saved in locales (not fetched through the core/api)

It should be added after the last news items in the log for all wallets. If filtering based on X months back happens, the item should not be displayed if it is older than that.

@triaslucia 
Questions:
Should these be different from shared wallet and personal wallet? Or should it only be in personal wallet timestamp?
Do you want the message in both logs but with the creation timestamp of the current wallet?

We need to check how easy it is to know the signup time for a wallet. Might need backend work to access information.

**Comment by JacqueGM** [comment]
Question from backend: what is the problem this feauture is trying to solve? Because there is already a welcome page.

**Comment by louilinn** [comment]
Too personalized item for a generic log, requires too much work around
