### ISSUE TITLE
Loading more mutual activities resets current scroll

### ISSUE THREAD

**Issue by juanenrisley** [CirclesUBI/circles-myxogastria#726]
When clicking on loading more, the view reloads all list of activities resetting the page scroll and having to scroll down again to see last mutual activities

**Comment by juanenrisley** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/circles-myxogastria/726?planning-poker) with Zenhub @louilinn @mikozet

**Comment by mikozet** [comment]
Probably happens because once we load activities we show only loader which than cause that page doesn't need to have scroll and once new items are loaded we end up at top page..
Solution could be that we add loader below activities while still showing them..
