### ISSUE TITLE
Sending any transaction ends up with a duplicated notification

### ISSUE THREAD

**Issue by juanenrisley** [CirclesUBI/circles-myxogastria#757]
Doing any kind of operation that sends a blockchain transaction ends up with a duplicated notification.

![bug-notifications](https://github.com/CirclesUBI/circles-myxogastria/assets/21304460/1d0a2b80-f83d-4095-8d9c-052972b48866)

**Comment by louilinn** [comment]
> Doing any kind of operation that sends a blockchain transaction ends up with a duplicated notification.
> 
> 
Is the duplicated notification only related to non-done transaction or does it persist after reload (when transaction is done)?

**Comment by juanenrisley** [comment]
> Is the duplicated notification only related to non-done transaction or does it persist after reload (when transaction is done)?

Only the temporary notification is duplicated. There is no persisted duplication on the blockchain.

**Comment by llunaCreixent** [comment]
The duplicated transaction for a transfer appears once with the note text, and the other without it. After refreshing the version without the note is the one that stays. And non of the transfer notifications have the note
