### ISSUE TITLE
Bug: There is no recovery from state where safe deployment succeeds but token deployment fails

### ISSUE THREAD

**Issue by ana0** [CirclesUBI/circles-myxogastria#81]
The user with safe "0x17ad56c34c7ea58599e9d73d94b14542f260f3e8" successfully received three trust connections, and deployed their safe but for whatever reason their token does not look like it was ever deployed. They're stuck on https://github.com/CirclesUBI/circles-baby-phoenix/blob/f41950a79f4b5ac898f2ab63de5a09f7fbbc6be8/src/store/token/actions.js#L82 and can't recover/use their account

The app should recover in some way from this case, either by allowing them to restart the deployment manually, or restarting it automatically in the background

**Comment by adzialocha** [comment]
Fixed via https://github.com/CirclesUBI/circles-baby-phoenix/commit/b7036c707b0ab214f91b7e6f32067626c93964f0
